### ISSUE TITLE
mt030d - `Edition.mintBatch()` could fail due to forwarding `msg.value` in a loop

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#100]
mt030d

high

# `Edition.mintBatch()` could fail due to forwarding `msg.value` in a loop

## Summary

`Edition.mintBatch()` forwards `msg.value` in each iteration of a loop. If the loop runs more than one iteration, the function fails.

## Vulnerability Detail
```solidity
    /// @notice Mint multiple tokens for the given works.
    /// @param to_ The address to mint the tokens to.
    /// @param tokenIds_ The IDs of the works to mint.
    /// @param amounts_ The amounts of each work to mint.
    /// @param data_ The data associated with the mint. Reserved for future use.
    function mintBatch(
        address to_,
        uint256[] calldata tokenIds_,
        uint256[] calldata amounts_,
        bytes calldata data_
    ) external payable {
        for (uint256 i = 0; i < tokenIds_.length; i++) {
            Work storage work = works[tokenIds_[i]];

            // wake-disable-next-line reentrancy
            FEE_MANAGER.collectMintFee{value: msg.value}(
                this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
            );

            _checkTime(work.opensAt, work.closesAt);
            _updateSupply(work, amounts_[i]);
        }

        _batchMint(to_, tokenIds_, amounts_, data_);
        _refundExcess();
    }
```
The ﻿`mintBatch()` function in the ﻿`Edition` contract iterates over the inputted `﻿tokenIds_`. In each iteration, it forwards ﻿`msg.value` to the ﻿`FEE_MANAGER.collectMintFee()` call.
On the first iteration, the function sends ﻿`msg.value` to ﻿`FEE_MANAGER`. However, on the second iteration, it reverts due to insufficient funds, assuming the `Edition` contract has a zero balance.
In summary, the ﻿`mintBatch()` call fails when the length of the ﻿`tokenIds_` input is more than one.

## Impact

The ﻿`mintBatch()` call fails when the length of the ﻿`tokenIds_` input is more than one.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L277-L297

## Tool used

Manual Review

## Recommendation
In `mintBatch()`, only forward the necessary fee to the ﻿FEE_MANAGER in each iteration of the loop.

Duplicate of #280

**Comment by TradMod** [comment]
Escalate

This finding is a valid dup of #280

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This finding is a valid dup of #280 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #280

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #280

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-04-titles-judging/issues/100/#issuecomment-2106796278): accepted
