### ISSUE TITLE
cducrest-brainbot - mintBatch() function cannot mint batch with mint fee

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#109]
cducrest-brainbot

medium

# mintBatch() function cannot mint batch with mint fee

## Summary

The Edition function `mintBatch()` that attempts to mint a list of token ids and amounts to a single receiver will not be able to pay the mint fee as the first iteration of the mint loop sends the total `msg.value` to the `FEE_MANAGER` contract and the FeeManager does not reimburse the Edition.

The second call to FeeManager using `msg.value` will fail as the Edition will not hold enough funds.

## Vulnerability Detail

For a non-zero `msg.value`, this function will revert:

```solidity
    function mintBatch(
        address to_,
        uint256[] calldata tokenIds_,
        uint256[] calldata amounts_,
        bytes calldata data_
    ) external payable {
        for (uint256 i = 0; i < tokenIds_.length; i++) {
            Work storage work = works[tokenIds_[i]];

            // wake-disable-next-line reentrancy
            FEE_MANAGER.collectMintFee{value: msg.value}(  // @audit msg.value sent in a loop
                this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
            );

            _checkTime(work.opensAt, work.closesAt);
            _updateSupply(work, amounts_[i]);
        }

        _batchMint(to_, tokenIds_, amounts_, data_);
        _refundExcess();
    }
```

## Impact

Users are not able to mint batches of tokens on an edition.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L277-L297

## Tool used

Manual Review

## Recommendation

Calculate the exact fee to send and only send appropriate amounts. Otherwise make FeeManager return the unused ether.

Duplicate of #280

**Comment by cducrest** [comment]
Escalate

Obvious duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/280

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Obvious duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/280

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #280

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #280

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cducrest](https://github.com/sherlock-audit/2024-04-titles-judging/issues/109/#issuecomment-2107377828): accepted
