### ISSUE TITLE
jecikpo - Possible loss of Ether during Edition creation

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#112]
jecikpo

medium

# Possible loss of Ether during Edition creation

## Summary
A user who calls the `TitlesCore.createEdition()` is required to the pay the creation fee with Ether that is sent to the contract during function call. If the amount of Ether is larger than the required fee, then the remaining amount will stay on the `FeeManager`.
## Vulnerability Detail
During  `TitlesCore.createEdition()` eventually the `_publish()` gets called which will transfer the entire `msg.value` to the `FeeManager`:
```solidity
feeManager.collectCreationFee{value: msg.value}(edition_, tokenId, msg.sender);
```
The fee at the `FeeManager` shall be first calculated by the `getCreationFee()` and sent to the `protocolFeeReceiver` by the `_route()` function.

The excess Ether that is left on the `FeeManager` could either be withdrawn by the protocol team using `withdraw()` or it could be used by the next minter who could just supply the remaining Ether during minting so that his Ether sent + the Ether sitting on `FeeManager` could be just enough to satisfy the necessary fee amount.

## Impact
Loss of excess Ether by the Edition creator.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/TitlesCore.sol#L138

## Tool used
Manual Review

## Recommendation
It is recommended to send exact amount of ether by the `_publish()` function, the change would be: 
```diff
// Collect the creation fee
        // wake-disable-next-line reentrancy
-        feeManager.collectCreationFee{value: msg.value}(edition_, tokenId, msg.sender);
+        feeManager.collectCreationFee{value: feeManager.getCreationFee().amount}(edition_, tokenId, msg.sender);
```
Next, excess Ether needs to be brought back to the `msg.sender` in similar way as it is done in the minting functions in `Edition`:
```diff
+function _refundExcess() internal {
+        if (msg.value > 0 && address(this).balance > 0) {
+            msg.sender.safeTransferETH(address(this).balance);
+        }
+    }
```

And the function call be added at the end of `_publish()`:

```diff
    function _publish(Edition edition_, WorkPayload memory work_, address referrer_)
        internal
        returns (uint256 tokenId)
    {
        [...]
        // Set the royalty target for the new Work
        // wake-disable-next-line reentrancy
        edition_.setRoyaltyTarget(tokenId, feeReceiver.target);
+       _refundExcess();
    }
```

**Comment by pqseags** [comment]
I would say this is medium, as it allows people to mint without paying.

**Comment by ghost** [comment]
Escalate
On behalf of Sponsors

**Comment by sherlock-admin3** [comment]
> Escalate
> On behalf of Sponsors

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by jecikpo** [comment]
I think that this should be a valid issue as on the `Edition` contract there is a function called `_refundExcess()` which is used to transfer back the excess amount of Ether (if the user supplied too much) hence there is a clear intent from the protocol on how to handle excess payments.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by WangSecurity** [comment]
Excuse me, I believe this should remain invalid. Creation fee can only be changed by the owner, hence, there are two scenario's this issue may occur:

1. User mistakenly sends more msg.value than creation fee -- user mistake
2. Admin accidentally changes the fee right before the user creates the work -- admins are trusted, hence, this scenario is not viable.

While in situation with mint fee, it's changed with by the work creator, who is not trusted. Planning to reject the escalation.

**Comment by jecikpo** [comment]
As per my previous comment, other functionalities specifically own mechanism for excess Ether return, so the protocol would be inconsistent. 

Regarding user mistake, the user is not going to put the value there on their own, the front-end is going to do it for them. If the front-end has a bug and calculates excessive amount those founds will be lost by the user and the protocol would be to blame. Lack of this safeguard introduces a potential attack vector on the protocol and its users. Hence I think this is a valid issue and should be fixed. Return of excess Ether is generally a best practice among smart contract designs.

**Comment by WangSecurity** [comment]
Firstly, if there is eth returh for this mechanism, it doesn't mean there should be for another. I believe it's design decision.

Secondly, it's user responsibility to provide as much gas as they want, hence, it's user mistake if they send more msg.value, moreover, it's an opportunity loss to get refund of gas.

Hence, decision remains the same, reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Hash01011122](https://github.com/sherlock-audit/2024-04-titles-judging/issues/112/#issuecomment-2107077230): rejected
