### ISSUE TITLE
kennedy1030 - The excess Ether in the call to `Edition.mint()` is not returned to `msg.sender`.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#119]
kennedy1030

high

# The excess Ether in the call to `Edition.mint()` is not returned to `msg.sender`.

## Summary

The excess Ether in the call to `Edition.mint()` is not returned to msg.sender.

## Vulnerability Detail

In the call to `Edition.mint()`, it transfers the full `msg.value` to the `FEE_MANAGER`, but the `FEE_MANAGER` has no refund mechanism.

```solidity
    function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
@>      FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );

        _issue(to_, tokenId_, amount_, data_);
@>      _refundExcess();
    }
```

As a result, since there is no remaining Ether left in the `Edition` contract, the `_refundExcess()` function cannot refund any excess Ether.

```solidity
    function _refundExcess() internal {
        if (msg.value > 0 && address(this).balance > 0) {
            msg.sender.safeTransferETH(address(this).balance);
        }
    }
```

## Impact

The excess ETH is not returned to `msg.sender`.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L242

## Tool used

Manual Review

## Recommendation

```diff
    function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
-       FEE_MANAGER.collectMintFee{value: msg.value}(
+       FEE_MANAGER.collectMintFee{value: mintFee(tokenId_, amount_)}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );

        _issue(to_, tokenId_, amount_, data_);
        _refundExcess();
    }
```

Duplicate of #269

**Comment by kennedy1030** [comment]
Escalate
This is a duplicate of #269. Check again, please.

**Comment by sherlock-admin3** [comment]
> Escalate
> This is a duplicate of #269. Check again, please.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by FastTiger777** [comment]
Escalate
I think this issue is valid and  [#124 ](https://github.com/sherlock-audit/2024-04-titles-judging/issues/124) is also a duplicate of this issue.

**Comment by sherlock-admin3** [comment]
> Escalate
> I think this issue is duplicate of  [#124 ](https://github.com/sherlock-audit/2024-04-titles-judging/issues/124).

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kennedy1030](https://github.com/sherlock-audit/2024-04-titles-judging/issues/119/#issuecomment-2106269889): accepted
