### ISSUE TITLE
FastTiger - DOS in function `Edition.sol#mintBatch()`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#123]
FastTiger

medium

# DOS in function `Edition.sol#mintBatch()`

## Summary
In the `Edition.sol#mintBatch()` function, DOS occurs because the amount of ETH (`msg.value`) that `Edition` receives from the caller is smaller than the amount of ETH transferred to `FeeManager`.
## Vulnerability Detail
The `Edition.sol#mintBatch()` function is as follows.
```solidity
    function mintBatch(
        address to_,
        uint256[] calldata tokenIds_,
        uint256[] calldata amounts_,
        bytes calldata data_
    ) external payable {
283:    for (uint256 i = 0; i < tokenIds_.length; i++) {
284:        Work storage work = works[tokenIds_[i]];

            // wake-disable-next-line reentrancy
287:        FEE_MANAGER.collectMintFee{value: msg.value}(
288:            this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
289:        );

291:        _checkTime(work.opensAt, work.closesAt);
292:        _updateSupply(work, amounts_[i]);
293:    }

        _batchMint(to_, tokenIds_, amounts_, data_);
        _refundExcess();
    }
```
As you can see, the amount of ETH that `Edition` receives from the caller is `msg.value`.
However, in #L283 ~ #L293, ETH corresponding to `msg.value` is repeatedly transferred to `FeeManager`.
In other words, if the amount received from the caller is `1 ETH` and the work to be minted is 5, `msg.value * 5 = 5 ETH` must be transferred to `FeeManager`. 
However, since `msg.value = 1ETH` and we call `_refundExcess()` function after mint works, the ETH balance of `Edition` is 1ETH and as a result, DOS occurs.
## Impact
In the `Edition.sol#mintBatch()` function, a permanent DOS occurs due to insufficient ETH balance.
## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L277-L297
## Tool used

Manual Review

## Recommendation
Modify the `Edition.sol#mintBatch()` function as follows.
```solidity
    function mintBatch(
        address to_,
        uint256[] calldata tokenIds_,
        uint256[] calldata amounts_,
        bytes calldata data_
    ) external payable {
        for (uint256 i = 0; i < tokenIds_.length; i++) {
            Work storage work = works[tokenIds_[i]];

            // wake-disable-next-line reentrancy
---         FEE_MANAGER.collectMintFee{value: msg.value}(
---             this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
---         );

+++         FEE_MANAGER.collectMintFee{value: FEE_MANAGER.getMintFee(work.strategy, amount_[i])}(
+++             this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
+++         );

            _checkTime(work.opensAt, work.closesAt);
            _updateSupply(work, amounts_[i]);
        }

        _batchMint(to_, tokenIds_, amounts_, data_);
        _refundExcess();
    }
```

Duplicate of #280

**Comment by TradMod** [comment]
Escalate

This finding is a valid dup of #280

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This finding is a valid dup of #280 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #280

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #280

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-04-titles-judging/issues/123/#issuecomment-2106809353): accepted
