### ISSUE TITLE
FastTiger - In the `FeeManager.sol#collectMintFee()` function, the remaining funds are not refunded under certain conditions.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#124]
FastTiger

medium

# In the `FeeManager.sol#collectMintFee()` function, the remaining funds are not refunded under certain conditions.

## Summary
When the `Edition.sol#mint()` function is called, under certain conditions, the `FeeManager.sol#setProtocolFees()` or `Edition.sol#setFeeStrategy()` function is performed before this function, and the fee portion that the caller must pay It may be smaller than this prediction.
In this case, the caller may incur a loss in fee payment because the remaining funds are not repaid in the `FeeManager.sol#collectMintFee()` function.
## Vulnerability Detail
In the `Edition.sol#mint()` function, the entire fee paid by the caller (`msg.value`) is sent to `FeeManager` using the `collectMintFee()` function.
```solidity
    function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
236:    FEE_MANAGER.collectMintFee{value: msg.value}(
237:        this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
237:    );

        _issue(to_, tokenId_, amount_, data_);
241:    _refundExcess();
    }
```
And then, call the `_refundExcess()` function to refund any excess ETH sent to the contract in #L241.
The `_refundExcess()` function is called after minting tokens to refund any ETH left in the contract after all fees have been collected.
However, there is no remaining funds repayment part in the `FeeManager.sol#collectMintFee()` function.
```solidity
    function collectMintFee(
        IEdition edition,
        uint256 tokenId_,
        uint256 amount_,
        address payer_,
        address referrer_,
        Strategy calldata strategy_
    ) external payable {
        _collectMintFee(
            edition, tokenId_, amount_, payer_, referrer_, getMintFee(strategy_, amount_)
        );
    }
```
When the `mint()` function is called from a dApp, the transaction waits in the mempool.
At this time, if the protocol admin calls the `FeeManager.sol#setProtocolFees()` or `Edition.sol#setFeeStrategy()` function, it may be executed before the transaction called by the user on the mempool.
Because of this, the fee required to `mint` an Edition may be smaller than the fee paid by the user (`msg.value`).
However, in this case, the operation of the `_refundExcess()` itself in the `mint()` function where the adjustment fund is converted from the `collectMintFee()` function is not performed smoothly.
As a result, when residual funds arise, the user cannot receive a refund for the remaining funds in the manner implemented by the protocol. Therefore, users may end up paying more fees.
There is a `withdraw()` function in `FeeManager`, but this is a function that is used when the contract holds an asset that it should not hold, such as when the caller accidentally transfers funds to this contract. The protocol is designed to reimburse the caller for any remaining funds after paying the fee.
## Impact
If residual funds arise, the user will not receive a refund for these funds.
## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L183-L193
## Tool used

Manual Review

## Recommendation
The remaining funds repayment part must be added to the `FeeManager.sol#collectMintFee()` function.
```solidity
    function collectMintFee(
        IEdition edition,
        uint256 tokenId_,
        uint256 amount_,
        address payer_,
        address referrer_,
        Strategy calldata strategy_
    ) external payable {
        _collectMintFee(
            edition, tokenId_, amount_, payer_, referrer_, getMintFee(strategy_, amount_)
        );
+++     if(msg.value - getMintFee(strategy_, amount_) > 0){
+++         msg.sender..safeTransferETH(msg.value - getMintFee(strategy_, amount_));
+++     }
    }
```

Duplicate of #269

**Comment by TradMod** [comment]
Escalate

This finding is a valid dup of #269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This finding is a valid dup of #269

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-04-titles-judging/issues/124/#issuecomment-2106810691): accepted
