### ISSUE TITLE
kennedy1030 - The `Edition.mintBatch()` function pays less fees than expected.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#126]
kennedy1030

high

# The `Edition.mintBatch()` function pays less fees than expected.

## Summary

`Edition::mintBatch` only receives the price for one buyer.

## Vulnerability Detail

In the `Edition.mintBatch()` function, the number of tokens minted for each `tokenId_` is `amount_ * receivers_`, but the fees are only taken for the `amount_` tokens.

```solidity
    function mintBatch(
        address[] calldata receivers_,
        uint256 tokenId_,
        uint256 amount_,
        bytes calldata data_
    ) external payable {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
@>          this, tokenId_, amount_, msg.sender, address(0), works[tokenId_].strategy
        );

        for (uint256 i = 0; i < receivers_.length; i++) {
            _issue(receivers_[i], tokenId_, amount_, data_);
        }

        _refundExcess();
    }
```

## Impact

Due to the issue with the `Edition.mintBatch()` function, the protocol, publishers, and collection referrers are receiving less fees than expected.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L304-L320

## Tool used

Manual Review

## Recommendation

```diff
    function mintBatch(
        address[] calldata receivers_,
        uint256 tokenId_,
        uint256 amount_,
        bytes calldata data_
    ) external payable {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
-           this, tokenId_, amount_, msg.sender, address(0), works[tokenId_].strategy
+           this, tokenId_, amount_ * receivers_.length, msg.sender, address(0), works[tokenId_].strategy
        );

        for (uint256 i = 0; i < receivers_.length; i++) {
            _issue(receivers_[i], tokenId_, amount_, data_);
        }

        _refundExcess();
    }
```

Duplicate of #264

**Comment by kennedy1030** [comment]
Escalate
This is a duplicate of #264. Check again, please.

**Comment by sherlock-admin3** [comment]
> Escalate
> This is a duplicate of #264. Check again, please.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #264

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #264

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kennedy1030](https://github.com/sherlock-audit/2024-04-titles-judging/issues/126/#issuecomment-2106271075): accepted
