### ISSUE TITLE
Lef - [M-01] Edition.sol:transferWork() #L412 uses single-step full ownership transfer of the work

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#127]
Lef

medium

# [M-01] Edition.sol:transferWork() #L412 uses single-step full ownership transfer of the work

## Summary
Single-step ownership transfer means that if a wrong address was passed when transferring ownership then it can mean that the creator of a work can be an unrecoverable address.

## Vulnerability Detail
Edition.sol:transferWork() allows the current creator of a work to transfer the work to a new creator. There is no check that the addresss is (0) or even the correct one. Mistakes can always happen and in this case they will be very costly.

## Likelihood
Low, because it requires an error on the current creator side

## Impact
High, because the current work will not have a creator which means no one can trigger important functions like changing work metadata, setting new timeframe (setTimefram()), changing fee strategy (setFeeStrategy()).

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L412

        function transferWork(address to_, uint256 tokenId_) external {
            Work storage work = works[tokenId_];
            if (msg.sender != work.creator) revert Unauthorized();
            Transfer the work to the new creator
            work.creator = to_;
            emit WorkTransferred(address(this), tokenId_, to_);
        }

## Tool used
Visual inspection

## Recommendation
It is a best practice to use two-step ownership transfer pattern, meaning ownership transfer gets to a "pending" state and the new creator should claim his new rights, otherwise the old creator still has control of the contract. Consider using OpenZeppelin's `Ownable2Step` contract

**Comment by ccashwell** [comment]
This isn't a contract transfer, just a single work within the contract. Users misdirecting a transfer of control of a work is not a concern.
