### ISSUE TITLE
mt030d - For each edition, only one collection referrer is stored in `FeeManager`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#129]
mt030d

high

# For each edition, only one collection referrer is stored in `FeeManager`

## Summary

The ﻿`FeeManager` should store referrers on a per-work basis, but currently, it only stores one referrer per edition. This causes an issue: when publishing new works in an edition, the original referrer can be overridden, resulting in missed referrer fees for the original referrers.

## Vulnerability Detail

The collection referrers receives a share of mint fee when related work is minted. The current implementation of the codebase only stores one collection referrer per `Edition`. Specifically, it is stored in the `referrers` mapping in the `FeeManager` contract. 
```solidity
    /// @notice The mapping of referrers for each {Edition}'s creation.
    mapping(IEdition edition => address referrer) public referrers;
```

The referrer for an Edition is initialized when the user creates an `Edition` using `TitleCore.createEdition()` and inputs a `referrer_` value. However, when a user publishes a new work in the Edition by using `TitleCore.publish()`, the referrer for an Edition is reset to the new `referrer_` address inputted in `TitleCore.publish()`.

```solidity
    function publish(Edition edition_, bytes calldata payload_, address referrer_)
        external
        payable
        returns (uint256 tokenId)
    {
        ...
        return _publish(edition_, payload, referrer_);
    }
    function _publish(Edition edition_, WorkPayload memory work_, address referrer_)
        internal
        returns (uint256 tokenId)
    {
        ...
        Target memory feeReceiver = feeManager.createRoute(
            edition_, tokenId, _attributionTargets(work_.attributions), referrer_
        );
        ...
    }
    function createRoute(
        IEdition edition_,
        uint256 tokenId_,
        Target[] calldata attributions_,
        address referrer_
    ) external onlyOwnerOrRoles(ADMIN_ROLE) returns (Target memory receiver) {
        ...
        referrers[edition_] = referrer_;
    }
```
The ﻿`referrer_` input to ﻿`TitlesCore.publish()` is forwarded to ﻿`TitlesCore._publish()` and then to `﻿FeeManager.createRoute()`, which updates the ﻿`referrers[edition_]` with the inputted ﻿`referrer_`.
Publishing new works in an edition updates the referrer in the edition. If the ﻿`referrer_` parameter in ﻿`publish()` is a new address, it overrides the ﻿`referrers[edition_]` state variable, preventing the initial referrer from receiving their fee share of minting.
For instance, I create an edition with Alice as the referrer. The edition has one work, and Alice is the referrer for this work, entitled to receive the referrer share of the mint fee. Then, I publish a second work with Bob as the referrer. Bob should only be the referrer for the second work but he now becomes the referrer for the edition. When users mint the first work from my edition, the collection referrer fee share should go to Alice, but it goes to Bob instead.

To put this issue in another way, since an edition can have multiple works, and each work can have its own collection referrer, it is more reasonable to store the referrer on a per-work basis (e.g., ﻿mapping(IEdition edition => mapping(uint256 tokenId => address referrer)) public referrers). However, the current codebase only stores the referrer on a per-edition basis, resulting in the collection referrer share of the minting fee not being distributed to the correct recipient.

## Impact

Publishing new works can override the referrer of the edition, causing previous referrers to miss their entitled referrer fees.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L104-L105

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/TitlesCore.sol#L103-L113

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/TitlesCore.sol#L120-L149

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L125-L160

## Tool used

Manual Review

## Recommendation
Store the referrer on a per-work basis, rather than per edition. Update the referrer setting logic and fee distribution logic accordingly.

Duplicate of #265

**Comment by mt030d** [comment]
Escalate
I believe this finding is a duplicate of #265 as they highlight the same impact, also the recommendation in #265 confirm the point made in this finding.

**Comment by sherlock-admin3** [comment]
> Escalate
> I believe this finding is a duplicate of #265 as they highlight the same impact, also the recommendation in #265 confirm the point made in this finding.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by TradMod** [comment]
Escalate

This finding is a valid dup of #265

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This finding is a valid dup of #265 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #265

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #265

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-04-titles-judging/issues/129/#issuecomment-2106818023): accepted
