### ISSUE TITLE
Yu3H0 - signature check can be passed in TitleGraphs——no nonce check in signature

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#133]
Yu3H0

high

# signature check can be passed in TitleGraphs——no nonce check in signature

## Summary
Signature Check can be passed in TitleGraphs

## Vulnerability Detail
acknowledgeEdge and unacknowledgeEdge have the version of using signature, but signature check is useless.

1. Because all the paremeters are controlled by users, and the check is the hash of the signature. So if a user can get a valid signature, then he can get another valid signature. https://hackernoon.com/what-is-the-math-behind-elliptic-curve-cryptography-f61b25253da3
2. Because the signature doesn't have a nonce, so there is no order check. When a user get a signature, he can wait until other users use their signature and then submit his tx to use his signature. 

## Impact
Signature misuse

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L40
```solidity
  modifier checkSignature(bytes32 edgeId, bytes calldata data, bytes calldata signature) {
      bytes32 digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data)));
      if (
          !edges[edgeId].to.creator.target.isValidSignatureNowCalldata(digest, signature)
              || _isUsed[keccak256(signature)]
      ) {
          revert Unauthorized();
      }
      _;
      _isUsed[keccak256(signature)] = true;
  }
```

## Tool used

Manual Review

## Recommendation
Add a nonce check or timestamp in signature

Duplicate of #279

**Comment by MageIntern** [comment]
Escalate

it is dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/279, not 284. and 279 is not dup as 273

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> it is dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/279, not 284. and 279 is not dup as 273

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #279

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #279

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [MageIntern](https://github.com/sherlock-audit/2024-04-titles-judging/issues/133/#issuecomment-2106709968): accepted
