### ISSUE TITLE
1337 - A signature can be used to both unacknowledgeEdge and acknowledgeEdge in TitlesGraph

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#135]
1337

high

# A signature can be used to both unacknowledgeEdge and acknowledgeEdge in TitlesGraph

## Summary
A signature can be used to both unacknowledgeEdge and acknowledgeEdge in TitlesGraph.
## Vulnerability Detail
In TitlesGraph, both unacknowledgeEdge and acknowledgeEdge can be called if we have a valid signature. However, there is no field to record a signature is for acknowledgeEdge or unacknowledgeEdge, which means if a signature for acknowledgeEdge can also be used to unacknowledgeEdge. 
```solidity
  /// @notice Modified to check the signature for a proxied acknowledgment.
  modifier checkSignature(bytes32 edgeId, bytes calldata data, bytes calldata signature) {
      bytes32 digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data)));
      if (
          !edges[edgeId].to.creator.target.isValidSignatureNowCalldata(digest, signature)
              || _isUsed[keccak256(signature)]
      ) {
          revert Unauthorized();
      }
      _;
      _isUsed[keccak256(signature)] = true;
  }
```

```solidity
  function unacknowledgeEdge(bytes32 edgeId_, bytes calldata data_, bytes calldata signature_)
      external
      checkSignature(edgeId_, data_, signature_)
      returns (Edge memory edge)
  {
      return _setAcknowledged(edgeId_, data_, false);
  }
```

```solidity
  function acknowledgeEdge(bytes32 edgeId_, bytes calldata data_, bytes calldata signature_)
      external
      checkSignature(edgeId_, data_, signature_)
      returns (Edge memory edge)
  {
      return _setAcknowledged(edgeId_, data_, true);
  }
```

## Impact
An attacker can front run to prevent acknowledgeEdge by call unacknowledgeEdge first using same signature. Also, we can apply a signature for unacknowledgeEdge but we can use it to acknowledgeEdge.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L41
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L118
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L146

## Tool used
Manual Review

## Recommendation
Add a field `ack` in Typed Data to indicate whether a signature is for acknowledgeEdge or unacknowledgeEdge.
```solidity
bytes32 digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data, ack)));
```

Duplicate of #273

**Comment by ccashwell** [comment]
This is not valid. `_isUsed` tracks signature usage, so it's not possible to replay the same signature for both types of calls.

**Comment by F01ivor4** [comment]
I mean front run, not replay, so it is duplicate https://github.com/sherlock-audit/2024-04-titles-judging/issues/273

> This is not valid. `_isUsed` tracks signature usage, so it's not possible to replay the same signature for both types of calls.

**Comment by F01ivor4** [comment]
Escalate

It is duplicate https://github.com/sherlock-audit/2024-04-titles-judging/issues/273

**Comment by soga061** [comment]
Escalate

It is duplicate https://github.com/sherlock-audit/2024-04-titles-judging/issues/273

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> It is duplicate https://github.com/sherlock-audit/2024-04-titles-judging/issues/273

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by MageIntern** [comment]
Escalate

It is duplicate https://github.com/sherlock-audit/2024-04-titles-judging/issues/273

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> It is duplicate https://github.com/sherlock-audit/2024-04-titles-judging/issues/273

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by soga061** [comment]
> This is not valid. `_isUsed` tracks signature usage, so it's not possible to replay the same signature for both types of calls.

I mean front run, not replay

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #273

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #273

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [MageIntern](https://github.com/sherlock-audit/2024-04-titles-judging/issues/135/#issuecomment-2106506783): accepted
