### ISSUE TITLE
cducrest-brainbot - FeeManager._splitProtocolFee() uses wrong collection referrer fee recipient

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#137]
cducrest-brainbot

high

# FeeManager._splitProtocolFee() uses wrong collection referrer fee recipient

## Summary

The function that splits the protocol fee among mint referrer, creation referrer, and protocol sends the collection referrer share to the mint referrer instead of the edition's referrer.

## Vulnerability Detail

The function `_splitProtocolFee()` calculates the fee split using `referrer_` (mint referrer) and ` referrers[edition_]` (edition referrer) address but only use `referrer_` address when routing the fees:

```solidity
    function _splitProtocolFee(
        IEdition edition_,
        address asset_,
        uint256 amount_,
        address payer_,
        address referrer_
    ) internal returns (uint256 referrerShare) {
        // The creation and mint referrers earn 25% and 50% of the protocol's share respectively, if applicable
        uint256 mintReferrerShare = getMintReferrerShare(amount_, referrer_);
        uint256 collectionReferrerShare = getCollectionReferrerShare(amount_, referrers[edition_]);
        referrerShare = mintReferrerShare + collectionReferrerShare;

        _route(
            Fee({asset: asset_, amount: amount_ - referrerShare}),
            Target({target: protocolFeeReceiver, chainId: block.chainid}),
            payer_
        );

        _route(
            Fee({asset: asset_, amount: mintReferrerShare}),
            Target({target: referrer_, chainId: block.chainid}),
            payer_
        );

        _route(
            Fee({asset: asset_, amount: collectionReferrerShare}),
            Target({target: referrer_, chainId: block.chainid}),  // @audit mint fee to wrong recipient, should be referrers[edition_]
            payer_
        );
    }
```

The edition's referrer is set when the route for the edition is created and can be different from the mint referrer which is user-provided at the time of the mint:

```solidity
    function createRoute(
        IEdition edition_,
        uint256 tokenId_,
        Target[] calldata attributions_,
        address referrer_
    ) external onlyOwnerOrRoles(ADMIN_ROLE) returns (Target memory receiver) {
        Target memory creator = edition_.node(tokenId_).creator;

        if (attributions_.length == 0) {
            // No attributions, pay the creator directly
            receiver = creator;
        } else {
            // Distribute the fee among the creator and attributions
            (address[] memory targets, uint256[] memory revshares) = _buildSharesAndTargets(
                creator, attributions_, edition_.feeStrategy(tokenId_).revshareBps
            );

            // Create the split. The protocol retains "ownership" to enable future use cases.
            receiver = Target({
                target: splitFactory.createSplit(
                    SplitV2Lib.Split({
                        recipients: targets,
                        allocations: revshares,
                        totalAllocation: 1e6,
                        distributionIncentive: 0
                    }),
                    address(this),
                    creator.target
                    ),
                chainId: creator.chainId
            });
        }

        _feeReceivers[getRouteId(edition_, tokenId_)] = receiver;
        referrers[edition_] = referrer_;
    }
```

## Impact

Edition referrer's fee is sent to the wrong recipient which is a guaranteed loss of funds to the edition's referrer.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L412-L441

## Tool used

Manual Review

## Recommendation

Replace `referrer_` with `referrers[edition_]` when routing `collectionReferrerShare` fee.

Duplicate of #267

**Comment by cducrest** [comment]
Escalate

Duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/267

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/267

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #267

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #267

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cducrest](https://github.com/sherlock-audit/2024-04-titles-judging/issues/137/#issuecomment-2107609612): accepted
