### ISSUE TITLE
BiasedMerc - Edition::transferWork() doesn't check for 0 address

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#14]
BiasedMerc

high

# Edition::transferWork() doesn't check for 0 address

## Summary

When users transfer a Work in `Edition::transferWork()`, there is no check to ensure that the `to_` address is not `address(0)`. If external users make a mistake, their Work will be unrecoverable (in terms of creator) and all future fees will be lost.

## Vulnerability Detail

A Work owner is able to transfer their Word to a new owner, however the `transferWork` function contains no check for the new owner being address 0. This function will be called by regular users, not protocol admins:

[Edition::transferWork()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L412-L420)
```solidity
    function transferWork(address to_, uint256 tokenId_) external {
        Work storage work = works[tokenId_];
        if (msg.sender != work.creator) revert Unauthorized();

        // Transfer the work to the new creator
        work.creator = to_;

        emit WorkTransferred(address(this), tokenId_, to_);
    }
```
Setting a Work's creator address to address(0) will cause the work to become unrecoverable and fees will be sent to the 0 address. As mentioned previously, the function is callable by normal users, therefore better protections should be put in place to protect users.

## Impact

Users may accidentally set `address(0)` when trying to transfer a Work to another creator, however due to no `address(0)` check, the call will succeed and the Work will be unrecoverable and fees will be lost. 

## Code Snippet

**[Edition::transferWork()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L412-L420)**

## Tool used

Manual Review

## Recommendation

Add a check to 
[Edition::transferWork()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L412-L420) ensuring the passed address is not the 0 address.
```diff
    function transferWork(address to_, uint256 tokenId_) external {
+      require(to_ != address(0), "to_ == address(0));
        Work storage work = works[tokenId_];
        if (msg.sender != work.creator) revert Unauthorized();

        // Transfer the work to the new creator
        work.creator = to_;

        emit WorkTransferred(address(this), tokenId_, to_);
    }
```

**Comment by ccashwell** [comment]
Not a concern. If the user wishes to burn ownership of their work, that's fine.
