### ISSUE TITLE
fibonacci - TitleGraph cannot be upgraded

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#142]
fibonacci

high

# TitleGraph cannot be upgraded

## Summary

The `TitleGraph` contract is intended to be upgradable; however, it is instantiated within the `TitlesCore::initialize` function without utilizing any proxy mechanism.

## Vulnerability Detail

The `TitleGraph` contract inherits from `UUPSUpgradeable` and implements the `_authorizeUpgrade` function. I have also consulted with the protocol team to confirm whether the contract is supposed to be upgradable, and they have confirmed this to be the case.

Despite this, the contract instance is created without employing an upgradeable proxy.

## Impact

The `TitleGraph` contract cannot be upgraded.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L17
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L217-L219
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L48

## Tool used

Manual Review

## Recommendation

The `TitleGraph` implementation should be created behind a proxy.

Duplicate of #445

**Comment by 0xf1b0** [comment]
Escalate

This is not a duplicate of issue #272. Possible duplicates are listed in issue #445.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is not a duplicate of issue #272. Possible duplicates are listed in issue #445.
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the escalation. This issue is a duplicate of #445.

**Comment by ghost** [comment]
Responded in #272 and #445.

Borderline low/medium. Tending towards low because in earlier contest issues like this were considered low.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #445

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xf1b0](https://github.com/sherlock-audit/2024-04-titles-judging/issues/142/#issuecomment-2107345016): accepted
