### ISSUE TITLE
0xboriskataa - `_refundExcess()` will not work as intended

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#151]
0xboriskataa

high

# `_refundExcess()` will not work as intended

## Summary
`_refundExcess()` is a function in `Edition.sol` that refunds the user any excess ETH that he sent to the contract:
```solidity
 function _refundExcess() internal {
        if (msg.value > 0 && address(this).balance > 0) {
            msg.sender.safeTransferETH(address(this).balance);
        }
    }
```
The issue is that this function will not actually return anything.

## Vulnerability Detail
`_refundExcess()` is called in functions used for minting tokens. However it is called after the `collectMintFee()` function which is from the `FEE_MANAGER` contract. Here is an example in `mint()`:
```solidity
function mint(address to_, uint256 tokenId_, uint256 amount_, address referrer_, bytes calldata data_) external payable override {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );

        _issue(to_, tokenId_, amount_, data_);
        _refundExcess();
    }
```
As we can see `collectMintFee()` is called with `msg.value`. In Solidity when you call a payable function in a contract, and that function calls another payable function in another contract, the ETH sent with the initial transaction (msg.value) stays within the execution context of the initial transaction until the second payable function (`collectMintFee()`) completes execution. If the second payable function executes successfully, the ETH will be transferred from the first contract to the second contract (`FEE_MANAGER`).

This means that the excess ETH the user sent and expected to get back will stay in the `FEE_MANAGER` contract and even after `_refundExcess()` he still won't get a refund because the excess ETH is not in this contract anymore.

## Impact
If user sends excess ETH because he trusts the system will refund him he will actually lose it.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L512-L516

## Tool used

Manual Review

## Recommendation
Use the `_refundExcess()` function in the `FeeManager.sol` contract insead

Duplicate of #269

**Comment by 0xjuaan** [comment]
Escalate

dupe of #269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> dupe of #269 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-04-titles-judging/issues/151/#issuecomment-2106537768): accepted
