### ISSUE TITLE
0xShiki - 0xShiki - `msg.value` is consumed in the first iteration of a for-loop in `mintBatch` function, preventing follow-up iterations from executing

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#152]
0xShiki

medium

# 0xShiki - `msg.value` is consumed in the first iteration of a for-loop in `mintBatch` function, preventing follow-up iterations from executing

0xShiki

medium

## Summary
`Editions` are ERC1155 contracts, in which each tokenId represents an individual work that has been published through the TITLES protocol. `mintBatch` function is used to mint to a `receiver` different amounts of different tokenIds to a user. However, when the `FeeManager` collects the mint fee for minting, it consumes the `msg.value` in the first iteration of the loop,  which can exhaust the available ETH balance after the first iteration.

```javascript
    function mintBatch(
        address to_,
        uint256[] calldata tokenIds_,
        uint256[] calldata amounts_,
        bytes calldata data_
    ) external payable {
        for (uint256 i = 0; i < tokenIds_.length; i++) {
            Work storage work = works[tokenIds_[i]];

            // wake-disable-next-line reentrancy
@>          FEE_MANAGER.collectMintFee{value: msg.value}(
                this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
            );

            _checkTime(work.opensAt, work.closesAt);
            _updateSupply(work, amounts_[i]);
        }

        _batchMint(to_, tokenIds_, amounts_, data_);
        _refundExcess();
    }
```

## Vulnerability Detail
Paste this test in `Edition.t.sol` file:

```javascript
    // In the `setUp` function
    edition.publish(
        address(2),
        10,
        0,
        0,
        new Node[](0),
        Strategy({
            asset: address(0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE),
            mintFee: 0.01 ether,
            revshareBps: 2500,
            royaltyBps: 250 
        }),
        Metadata({
            label: "Best2 Work2 Ever2",
            uri: "ipfs.io/best2-work2-ever2",
            data: new bytes(0)
        })
    );

    feeManager.createRoute(edition, 2, new Target[](0), address(0));
    .
    .
    .
    .
    .
    // Paste test
    function test_mintBatchMultipleWorksToReceiverReverts() public {
        uint256[] memory tokenIds = new uint256[](2);
        tokenIds[0] = 1;
        tokenIds[1] = 2;
        uint256[] memory amounts = new uint256[](2);
        amounts[0] = 1;
        amounts[1] = 1;
        edition.mintBatch{value: 0.0212 ether}(address(1), tokenIds, amounts, new bytes(0));
    }
```

The logs of the test show that the function reverts after the first iteration. If you divide the `msg.value` in the `mintBatch` function by 2, and run the test again, the test will pass.

## Impact
Disrupts the expected behavior of the smart contract function logic, preventing minting different tokenIds to a user, and also preventing the `FeeManager` from collecting mint fees for every tokenId.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L287

## Tool used
Manual Review

## Recommendation
Consider collecting the fees for each tokenId after minting all the tokenIds to the user.

Duplicate of #280

**Comment by TamarawGuy** [comment]
Escalate

The issue is a valid duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/280

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> The issue is a valid duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/280

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by sammy-tm** [comment]
Escalate

Dup of #280

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Dup of #280 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #280

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #280

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sammy-tm](https://github.com/sherlock-audit/2024-04-titles-judging/issues/152/#issuecomment-2106979805): accepted
