### ISSUE TITLE
radin200 - Minter of new Edition token could be able to pay lower fee due to missing `msg.value` validation

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#157]
radin200

medium

# Minter of new Edition token could be able to pay lower fee due to missing `msg.value` validation

## Summary
If `FeeManager` receive unexpected funds(e. g. left excess funds or donations), other users are now able to mint new Edition tokens at lower price

## Vulnerability Detail
Here you scenario:

1. Somebody mint tokens at higher msg.value(to be sure the transaction won't revert) or sends donation funds to `FeeManager`
2. User1 mints some new tokens from EditionA by calling `Edition.sol::mint` with msg.value LOWER than expected
3. EditionA executes `FeeManager.sol::collectMintFee`
4. `FeeManager.sol::collectMintFee`'s execution leads to `FeeManager.sol::_transfer`, which sends ETH directly from address(this)(`FeeManager`) to feeReceiver without checking `msg.value`
```solidity
function _transfer(address asset_, uint256 amount_, address from_, address to_) internal {
        if (asset_ == ETH_ADDRESS) {
            to_.safeTransferETH(amount_);
        } else {
            asset_.safeTransferFrom(from_, to_, amount_);
        }
    }

```

## Impact
Potential protocol/user loss of unexpected funds(e. g. left excess funds or donations)

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L242
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L461-L467

## Tool used

Manual Review

## Recommendation
One of the main solutions is to validate msg.value before any ETH transfers in `FeeManager.sol::_collectMintFee` as shown below:
```diff
function _collectMintFee(
        IEdition edition_,
        uint256 tokenId_,
        uint256 amount_,
        address payer_,
        address referrer_,
        Fee memory fee_ // @info fee_.amount = amount_ * (strategy_.mintFee + protocolFlatFee)
    ) internal {
        if (fee_.amount == 0) return;

        .....

        uint256 protocolFee = protocolFlatFee * amount_;
        uint256 protocolShare;
        if (fee_.amount == protocolFee) {
            protocolShare = protocolFee * protocolFeeshareBps / MAX_BPS;
        } else {
            protocolShare = protocolFee;
        }

+      if(msg.value < fee_.amount) revert();

        _route(
            Fee({asset: fee_.asset, amount: fee_.amount - protocolShare}),
            _feeReceivers[getRouteId(edition_, tokenId_)],
            payer_
        );

        uint256 referrerShare =
            _splitProtocolFee(edition_, fee_.asset, protocolShare, payer_, referrer_);
        emit FeeCollected(address(edition_), tokenId_, fee_.asset, fee_.amount, referrerShare);
    }
```

**Comment by radin200** [comment]
And why excluded?

**Comment by pqseags** [comment]
I think this should be included, ability to use funds stored in the contract to mint for less than the fee is a problem.

**Comment by novaman33** [comment]
Escalate

this should be included, ability to use funds stored in the contract to mint for less than the fee is a problem.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> this should be included, ability to use funds stored in the contract to mint for less than the fee is a problem.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Firstly, FeeManager is not expected to hold any unexpected funds besides the fees. Hence, the only two ways that there can be unexpected funds is either transferring them directly, i.e. user mistake, or due to an issue in mint function. This report doesn't explain how there can be excess funds, hence, the olny way is user mistake. Therefore, planning to reject the escalation and leave the issue as it is.

**Comment by radin200** [comment]
You are right, but there is function withdraw in feeManager, which has @notice 'An escape hatch to transfer any trapped assets from the contract to the given address.', so therefore we can clearly find that is intended to be trapped funds right in feeManager. So the term 'unexpected funds' is about funds, that are send in the contract by other contracts that are connected with the protocol.

**Comment by radin200** [comment]
For me this bug fix is more important than fundExceeds one, because stucked funds could be withdrawn back by admin anyway, of  course only if they can't be spend by other users with checking the msg.value. More of that when you fix the fundExceeds, the missing msg.value check problem is still on the table

**Comment by WangSecurity** [comment]
Firstly, trapped funds doesn't mean funds that are sent from other contracts of the protocol. Fees are tracked and not "trapped" and the only trapped funds that are sent there were explained in the previous message. Moreover, the code comment doesn't mean it's intended to have trapped funds, but is a saver function to withdraw funds that are not supposed to be in the FeeManager. How funds can get into FeeManager is explained in my previous comment. Hence, decision remains the same, reject the escalation and leave the issue as it is.

**Comment by radin200** [comment]
It is true that funds could be trapped only if there are directly send(connected contracts or users), but there is still unsolved problem with the broke practicability of the emergency function withdraw

**Comment by WangSecurity** [comment]
I'm not sure what you mean by "broke practicability". If you mean that the funds can be used before they're withdrawn or that it withdraws all the funds and fees as well. Then it doesn't change the fact of the user mistake or trusted admins. Moreover, as you can see the sponsor added a will fix label, so they're aware of this situation (remember that "sponsor confirmed" and "will fix" labels doesn't effect the reward distribution.

Hence, decision remains the same, reject the escalation and leave the issue as it is.

**Comment by radin200** [comment]
Under "broke practicability" I meant broke invariant. I agree with the rest of things

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [novaman33](https://github.com/sherlock-audit/2024-04-titles-judging/issues/157/#issuecomment-2107016476): rejected

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/titlesnyc/wallflower-contract-v2/pull/1
