### ISSUE TITLE
0xboriskataa - Collection referrers will get no fees because of incorrect reward distribution

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#158]
0xboriskataa

high

# Collection referrers will get no fees because of incorrect reward distribution

## Summary
There are two types of referrers that can exist within the protocol - a mint referrer and a collection referrer. They should both get fees if they have done refers but due to an error in the fees distribution the collection referrers will get nothing.

## Vulnerability Detail
Here is what one of the comments states:
```solidity
//   - If a referred mint, mint referrer gets 50% of the protocol share
//   - If a referred collection, collection referrer gets 25% of the protcol share
//   - Protocol fee receiver gets the remainder of the protocol share
```
The function `_splitProtocolFee()` is used to calculate these three portions and route (transfer) them to the appropriate addresses.

Here we calculate what each referrer should get:
```solidity
uint256 mintReferrerShare = getMintReferrerShare(amount_, referrer_);
uint256 collectionReferrerShare = getCollectionReferrerShare(amount_, referrers[edition_]);
```
As we can see from the second argument for each function the mint and collection referrers can be different addresses (this was also confirmed by a dev).

However during the fees distribution the 25% that the collection referrer is supposed to get actually goes to the mint refferer:
```solidity
_route(
  Fee({asset: asset_, amount: mintReferrerShare}),
  Target({target: referrer_, chainId: block.chainid}),  //target is mint referrer
  payer_
);

_route(
  Fee({asset: asset_, amount: collectionReferrerShare}),
  Target({target: referrer_, chainId: block.chainid}),  //target is again mint referrer
  payer_
);
```

## Impact
Mint referrers will get the fees that collection referrers should get instead.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L412-L441

## Tool used

Manual Review

## Recommendation
```diff
_route(
  Fee({asset: asset_, amount: mintReferrerShare}),
  Target({target: referrer_, chainId: block.chainid}),
  payer_
);

_route(
  Fee({asset: asset_, amount: collectionReferrerShare}),
- Target({target: referrer_, chainId: block.chainid}),
+ Target({target: referrers[edition_], chainId: block.chainid}),
  payer_
);
```

Duplicate of #267

**Comment by midori-fuse** [comment]
Escalate

Dupe of #267. Both correctly points out the issue of wrong distribution, the exact code location it happens, the same impact, and the same mitigation.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Dupe of #267. Both correctly points out the issue of wrong distribution, the exact code location it happens, the same impact, and the same mitigation.

You've deleted an escalation for this issue.

**Comment by sammy-tm** [comment]
Escalate

Dup of #267

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Dup of #267 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #267

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #267

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sammy-tm](https://github.com/sherlock-audit/2024-04-titles-judging/issues/158/#issuecomment-2110569155): accepted
