### ISSUE TITLE
techOptimizor - _refundExcess() wont work making users lose excess ETH sent during minting in Edition

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#159]
techOptimizor

high

# _refundExcess() wont work making users lose excess ETH sent during minting in Edition

## Summary
_refundExcess()  is a mechanism employped to refund excesses sent during minting in Edition but this does not work because of flaw in how Feemanager takes fee
## Vulnerability Detail
Each of the mint functions directly sends the whole msg.value to the feemanager and not the calculated fee a user is meant to pay .After the whole fee split  in the feemanager the excess are retained in the feemanager and not sent back to the Edition .
```solidity
    function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );

        _issue(to_, tokenId_, amount_, data_);
        _refundExcess();//@audit not refunded
    }
```
 This makes check for  _refundExcess() that address(this).balance > 0 false thereby making excess refund  never to trigger . 
```solidity
function _refundExcess() internal {
        if (msg.value > 0 && address(this).balance > 0) {
            msg.sender.safeTransferETH(address(this).balance);
        }
    }
```

## Impact
Loss of user funds 
## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L236

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L512C1-L517C2
## Tool used

Manual Review

## Recommendation
Either calculate the required fee and use it in call of feemanager collectfee 
Implement the refund fee in feemanager that refunds excesses back to the edition which will inturn return back to user

Duplicate of #269

**Comment by techOptimizor** [comment]
I was not active during thr escalation period so i could not report this 

I see no reason why this issue xiaoming90 - Excess ETH will be stuck in the Fee Manager contract and not swept back to the users #269 from xiaoming90 is accepted  and mine decline while we are basicslly saying same the 
Eth being stuck is caused by the refund logic  and thats same thing i pointed out but it was exclued 

https://github.com/sherlock-audit/2024-04-titles-judging/issues/269
