### ISSUE TITLE
radin200 - `Edition.sol`'s mint functions don't refund excess funds to minters

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#163]
radin200

high

# `Edition.sol`'s mint functions don't refund excess funds to minters

## Summary
Minter who decides to set bigger msg.value than expected will meet loss of funds

## Vulnerability Detail
Here you possible scenario: 

1. User decides to mint new Edition token by executing `Edition.sol::mint` and to be sure the transaction won't revert, he sends more ETH than expected
2. `Edition.sol::mint` calls `FeeManager::collectMintFee`, which does not return any exceeded funds, left from the fees collected from `Edition.sol`'s `msg.value`
3. Due to this `Edition.sol::_refundExcess()` won't be executed and the exceeded funds are left in `FeeManager`

Note that in this scenario `Edition` have 0 balance

4. Finally other Users are able to mint tokens at cheaper price

## Impact
User loss of funds due to exceeded funds not returned

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L242
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L183-L193
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L366-L410

## Tool used

Manual Review

## Recommendation
1. Implement `_refundExcess()` function in `FeeManager.sol`
```solidity
function _refundExcess(uint256 excesses) internal {
        if (msg.value > 0 && address(this).balance > 0) {
            msg.sender.safeTransferETH(msg.value - excesses);
        }
    }
```
2. modify collectFee functions as shown below:
```diff
function collectMintFee(
        IEdition edition,
        uint256 tokenId_,
        uint256 amount_,
        address payer_,
        address referrer_,
        Strategy calldata strategy_
    ) external payable {
+      Fee fee = getMintFee(edition_, tokenId_, amount_)
        _collectMintFee(
-            edition, tokenId_, amount_, payer_, referrer_, getMintFee(strategy_, amount_)
+            edition, tokenId_, amount_, payer_, referrer_, fee
        );
+     _refundExcess(msg.value - fee.amount)
    }        
``` 

Duplicate of #269

**Comment by radin200** [comment]
And why excluded?

**Comment by TradMod** [comment]
Escalate

dup of #269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> dup of #269

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-04-titles-judging/issues/163/#issuecomment-2106872906): accepted
