### ISSUE TITLE
AlexCzm - CollectionReferrerShare is wrongly sent to mint referrer

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#177]
AlexCzm

high

# CollectionReferrerShare is wrongly sent to mint referrer

## Summary
Collection referrer share is sent erroneously to the mint referrer instead of the collection referrer.

## Vulnerability Detail

`_splitProtocolFee` is used to split protocol fee  between `protocolFeeReceiver`,  mint referrer and Edition referrer.
CollectionReferrerShare is erroneously sent to mint referrer. 

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L437-L438

```solidity
    function _splitProtocolFee(
        IEdition edition_,
        address asset_,
        uint256 amount_,
        address payer_,
        address referrer_
    ) internal returns (uint256 referrerShare) {
        // The creation and mint referrers earn 25% and 50% of the protocol's share respectively, if applicable
        uint256 mintReferrerShare = getMintReferrerShare(amount_, referrer_);
        uint256 collectionReferrerShare = getCollectionReferrerShare(amount_, referrers[edition_]);
        referrerShare = mintReferrerShare + collectionReferrerShare;
        _route(
            Fee({asset: asset_, amount: amount_ - referrerShare}),
            Target({target: protocolFeeReceiver, chainId: block.chainid}),
            payer_
        );
        _route(
            Fee({asset: asset_, amount: mintReferrerShare}),
            Target({target: referrer_, chainId: block.chainid}),
            payer_
        );
        _route(
            Fee({asset: asset_, amount: collectionReferrerShare}),
            Target({target: referrer_, chainId: block.chainid}),// @audit collectionReferrerShare is sent to *MINT* referrer instead of the collection referrer
            payer_
        );
    }
```

## Impact
Collection referrer gets no reward while mint referrer is paid twice.

## Code Snippet
Provided in Vulnerability Detail.

## Tool used

Manual Review

## Recommendation
Send the share to correct address: 

```solidity
    function _splitProtocolFee(
        IEdition edition_,
        address asset_,
        uint256 amount_,
        address payer_,
        address referrer_
    ) internal returns (uint256 referrerShare) {
...
        _route(
            Fee({asset: asset_, amount: mintReferrerShare}),
            Target({target: referrer_, chainId: block.chainid}),
            payer_
        );

        _route(
            Fee({asset: asset_, amount: mintReferrerShare}),
-            Target({target: referrer_, chainId: block.chainid}),
+            Target({target: referrers[edition_], chainId: block.chainid}),
            payer_
        );
}
```

Duplicate of #267

**Comment by sammy-tm** [comment]
Escalate 

Dup of #267

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> Dup of #267 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #267

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #267

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sammy-tm](https://github.com/sherlock-audit/2024-04-titles-judging/issues/177/#issuecomment-2107362540): accepted
