### ISSUE TITLE
0x73696d616f - `TitlesGraph::checkSignature()` modifier is vulnerable to signature malleability, allowing the manipulation of `edge.acknowledged`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#178]
0x73696d616f

medium

# `TitlesGraph::checkSignature()` modifier is vulnerable to signature malleability, allowing the manipulation of `edge.acknowledged`

## Summary

`SignatureCheckerLib` from [Solady](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L7) does not protect against signature malleability, allowing an attacker to set `edge.acknowledged` using the malleable signature.

## Vulnerability Detail

Signature malleability is [possible](https://medium.com/draftkings-engineering/signature-malleability-7a804429b14a) if not enough precautions are taken as the elliptic curve is symmetric, which means that there are 2 valid signatures for each message. Given a previous known signature, it's easy to forge another valid signature for the same message (check the linked article before to see how). Thus, a `creator` may send a transaction to set `edge.acknowledged` (via `TitlesGraph::acknowledgeEdge()` or `TitlesGraph::unacknowledgeEdge()`) along with a signature and later change `edge.acknowledged` to the opposite value. After `edge.acknowledged` has been reset, an attacker can fetch the signature from the first interaction to manipulate `edge.acknowledged` back to the initial value.

Another reason that this attack works is the protocol is storing used signatures with the [_isUsed](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L49) mapping, which takes as key the signature. Thus, if another signature is valid for the same data, it will not be able to prevent this.

The `creator` or `entity` may undo the manipulation by calling one of `TitlesGraph::acknowledgeEdge()` or `TitlesGraph::unacknowledgeEdge()` that rely on `msg.sender` checks instead of signatures, but there is a window during which the attacker has manipulated `edge.acknowledged`, which should be valid according to the [docs](https://audits.sherlock.xyz/contests/326):

> In addition to the security of funds, we would also like there to be focus on the sanctity of the data in the TitlesGraph and the permissioning around it (only the appropriate people/contracts can signal reference and acknowledgement of reference).

## Impact

Manipulated `edge.acknowledged` by an attacker due to abusing signature malleability.

## Code Snippet

Solady's [SignatureCheckerLib](https://github.com/Vectorized/solady/blob/main/src/utils/SignatureCheckerLib.sol#L23):
```solidity
...
/// This implementation does NOT check if a signature is non-malleable.
...
```

## Tool used

Manual Review

## Recommendation

Either use the `ECSDA` [lib](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol#L137-L139) from Openzeppelin which checks signature malleability or implement a nonce system.

Duplicate of #279

**Comment by 0x73696d616f** [comment]
Escalate

This issue is not a duplicate of #273. The duplicate of #273 is #175.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #279

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #279

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2024-04-titles-judging/issues/178/#issuecomment-2106260877): accepted
