### ISSUE TITLE
0x73696d616f - `TitlesGraph` upgradeability will not work as it is not deployed behind a proxy

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#180]
0x73696d616f

high

# `TitlesGraph` upgradeability will not work as it is not deployed behind a proxy

## Summary

`TitlesGraph` implementation is deployed in `TitlesCore::initialize()`, but not behind a proxy, which will not allow it to be upgraded.

## Vulnerability Detail

In [TitlesCore::initialize()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L44), the `TitlesGraph` implementation is [deployed](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L48), but it's missing the deployment of the proxy and setting the proxy's implementation to `TitlesGraph`. Although `TitlesCore` does not actually call `graph` other than via the public getter, it passes its address to `edition`, when it is [initialized](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L83), which means that `Edition` will call the implementation directly.

From the contest [readme](https://github.com/sherlock-audit/2024-04-titles-0x73696d616f?tab=readme-ov-file#q-are-there-any-protocol-roles-please-list-them-and-provide-whether-they-are-trusted-or-restricted-or-provide-a-more-comprehensive-description-of-what-a-role-can-and-cant-doimpact), it's clear that `TitlesGraph` should be deployed behind a proxy:
> 2) Upgrade the contract to an arbitrary new implementation (via _authorizeUpgrade, inherited and overridden with auth check from Solady's UUPSUpgradeable) 

## Impact

As the implementation is used directly, it will not be possible to upgrade it.

## Code Snippet

[TitlesCore::initialize()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L48) only deploying the implementation.
```solidity
function initialize(address feeReceiver_, address splitFactory_) external initializer {
    ...
    graph = new TitlesGraph(address(this), msg.sender); // @audit also here
}
```

## Tool used

Manual Review

Vscode

## Recommendation

Deploy the proxy and then set its implementation using [ERC1967Factory](https://github.com/Vectorized/solady/blob/main/src/utils/ERC1967Factory.sol) from Solady.

Duplicate of #445

**Comment by 0x73696d616f** [comment]
Escalate

This issue is not a duplicate of #272, they are not even pointing to the same contract and are different issues.

**Comment by cvetanovv** [comment]
I agree with the escalation. This issue is a duplicate of #445.

**Comment by ghost** [comment]
Responded in #272 and #445.

Borderline low/medium. Tending towards low because in earlier contest issues like this were considered low.

**Comment by 0x73696d616f** [comment]
@Hash01011122 could you provide links to the issues you mention were similar and considered low from the previous contests? Would like to confirm if possible.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #445

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2024-04-titles-judging/issues/180/#issuecomment-2106263627): accepted
