### ISSUE TITLE
0x73696d616f - `TitlesGraph` is missing an `initialize()` function and is setting the `owner` and the `admin` in the constructor, having no `owner` or `admin` in the proxy

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#182]
0x73696d616f

high

# `TitlesGraph` is missing an `initialize()` function and is setting the `owner` and the `admin` in the constructor, having no `owner` or `admin` in the proxy

## Summary

`TitlesGraph` is missing an `initialize()` function to set the `owner` and/or the `admin`, which would leave the proxy without `owner` or `admin`.

## Vulnerability Detail

`owner` and `admin` are set in `TitlesGraph::constructor()`, in the implementation's storage. Thus, when the implementation is called through the proxy's delegatecall, `owner` and `admin` will not be assigned and all the permissioned functions by these roles are not going to work, namely all that use roles and upgradeability functionality.

## Impact

Permissioned functions by the `owner` or `admin` are not reachable.

## Code Snippet

The `initialize()` function is missing in `TitlesGraph`, so the code can not be linked. However, it can be seen that the constructor executes the logic that should have been in `initialize()` instead.
[TitlesGraph::constructor](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L52-L55)
```solidity
constructor(address owner_, address admin_) {
    _initializeOwner(owner_);
    _grantRoles(admin_, ADMIN_ROLE);
}
```

## Tool used

Manual Review

Vscode

## Recommendation

Implement the `initialize()` function:
```solidity
function initialize(address owner_, address admin_) external initializer {
    _initializeOwner(owner_);
    _grantRoles(admin_, ADMIN_ROLE);
}
```

Duplicate of #445

**Comment by 0x73696d616f** [comment]
Escalate

This issue is not a duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/272. This one describes how the admin and owner of the proxy will never be set for `TitlesGraph`. #272 mentions how the implementation of `TitlesCore` is left uninitialized.

**Comment by WangSecurity** [comment]
Agree with the escalation and believe it should be a duplicate of #445. Planning to accept and duplicate accordingly.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #445

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2024-04-titles-judging/issues/182/#issuecomment-2106264458): accepted
