### ISSUE TITLE
ydlee - Excess mint fees are not returned to the minter as expected.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#184]
ydlee

high

# Excess mint fees are not returned to the minter as expected.

## Summary
Excess mint fees are transfered to the `FeeManager`, and are not returned to minter.

## Vulnerability Detail
As shown in `Edition.mint`, when minting a new token for a work, one needs to pay a certain amount of ETH as the mint fee. If the ETH paid exceeds the mint fee, it is expected that the excess will be returned to the minter. However, the excess mint fees go to `FeeManager`, and are not refunded to the minter.
1. When `Edition.mint` is called, all the paid ETH are sent to `Edition`, so `Edition.balance = msg.value`.
2. On line 236, all the paid ETH (i.e. `msg.value`) are sent to `FeeManager` contract to collect mint fees, so `Edition.balance = 0`.
3. After collecting mint fees, `FeeManager.collectMintFee` does not refund excess mint fees to `Edition` contract, so `Edition.balance = 0`.
4. On line 241, there is no ETH to refund to minter, as `Edition.balance = 0`.
```solidity
228:    function mint(
229:        address to_,
230:        uint256 tokenId_,
231:        uint256 amount_,
232:        address referrer_,
233:        bytes calldata data_
234:    ) external payable override {
235:        // wake-disable-next-line reentrancy
236:@>      FEE_MANAGER.collectMintFee{value: msg.value}(
237:            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
238:        );
239:
240:        _issue(to_, tokenId_, amount_, data_);
241:        _refundExcess();
242:    }
```
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L242

The following test case shows the problem (add it to `Edition.t.sol`).
```solidity
    function test_mint_refund() public {
        // balance before `mint`
        uint256 thisBalance1 = address(this).balance;
        uint256 feeManagerBalance1 = address(feeManager).balance;

        // mint fee should be 0.0106 ether
        assertEq(edition.mintFee(1), 0.0106 ether);

        // mint with 1.0106 ether, 1 ether should be refunded
        edition.mint{value: 1.0106 ether}(address(1), 1, 1, address(0), new bytes(0));
        assertEq(edition.totalSupply(1), 1);
        assertEq(address(1).balance, 0.01 ether);
        assertEq(address(0xc0ffee).balance, 0.0006 ether);

        // balance after `mint`
        uint256 thisBalance2 = address(this).balance;
        uint256 feeManagerBalance2 = address(feeManager).balance;

        // user paid 1.0106 ether, 1 ether is not refunded
        assertEq(thisBalance1 - thisBalance2, 1.0106 ether);

        // fee manager received the 1 ether
        assertEq(feeManagerBalance2 - feeManagerBalance1, 1 ether);
    }
```

This problem also exists for other mint functions (i.e. `Edition.mintWithComment` and `Edition.mintBatch`).

## Impact
Minters may suffer fee losses because excess minting fees are not returned to them as expected.

## Code Snippet
`Edition.mint()`:
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L242

`Edition.mintWithComment()`:
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L252-L270

`Edition.mintBatch()`:
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L277-L297

`Edition.mintBatch()`:
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L304-L320

## Tool used

Manual Review

## Recommendation
`FeeManager` refunds the excess mint fees to `Edition`, then `Edition` will refunds them to minter.

Duplicate of #269

**Comment by YD-Lee** [comment]
Escalate

Dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/269

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [YD-Lee](https://github.com/sherlock-audit/2024-04-titles-judging/issues/184/#issuecomment-2110539971): accepted
