### ISSUE TITLE
kennedy1030 - The `Edition` contract's minting functions should be protected against reentrancy attacks.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#185]
kennedy1030

high

# The `Edition` contract's minting functions should be protected against reentrancy attacks.

## Summary

The `Edition._refundExcess()` function is intended to refund any excess ETH sent during the minting process in the `Edition` contract. However, the minting functions are not properly protected against reentrancy attacks. As a result, this reentrancy vulnerability allows referrers and creators to steal the excess ETH sent during the minting process in the `Edition` contract.

## Vulnerability Detail

"The `_refundExcess()` function is intended to return any excess ETH sent during the minting process to the original `msg.sender`.

```solidity

    function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );

        _issue(to_, tokenId_, amount_, data_);
        _refundExcess();
    }

    function _refundExcess() internal {
        if (msg.value > 0 && address(this).balance > 0) {
            msg.sender.safeTransferETH(address(this).balance);
        }
    }

```
However, reentrancy is not prevented in the minting fucntions. Additionally, referers receive ETHs as fee. Creators without attributions receive ETHs directly, too. This make it possible for them to reenter the minting functions. Reentrancy in the minting functions calls `_refundExcess()` and all the excess ETHs is given to referers, not to buyers.

Suppose the following scenario:

1. A referer is a smart contract, not a EOA.
2. It has the reentrancy code in its `recieve()` function, which includes the call to the minting functions of `Edition` contract. 
```solidity

    receive() external payable {
        edition.mintBatch{value: 1wei}(to, uint256[](0), uint256[](0), "");
    }

```
Setting `{value: 1wei}` is for passing the check `msg.value > 0` in the `_refundExcess()` function.
3. A buyer mint a token whose referer is the above one.
4. Then all the excess ETHs of the buyer plus 1wei is given to the above referer.

This attack would not work well, because all ETHs are transfer to `FeeManager` now. I think that ETHs needed for minting should be sent to `FeeManager` before minting. 
If issues related refund is fixed by building refunding mechanism in `FeeManager`, the entrancy attack should be modified.
Then this attack will work after all issues related minting are fixed.

## Impact

Referers and creators can steal excess ETHs in the minting functions.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L512-L516

## Tool used

Manual Review

## Recommendation

Reentrancy in minting functions should be prevented.

Duplicate of #268

**Comment by kennedy1030** [comment]
Escalate
I think that this issue is a duplicate of #268.

**Comment by cvetanovv** [comment]
I agree with the escalation. This issue is a duplicate of #268.

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #268

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kennedy1030](https://github.com/sherlock-audit/2024-04-titles-judging/issues/185/#issuecomment-2106265089): accepted

**Comment by kennedy1030** [comment]
I think that this issue should remain valid even though #268 is invalidated. 
This issue pointed out the following comments:
"This attack would not work well, because all ETHs are transfer to FeeManager in the current version. I think that ETHs needed only for minting should be sent to FeeManager before minting.
If issues related refund is fixed by building refunding mechanism in FeeManager, the entrancy attack should be modified."
This issue clearly pointed out that it is necessary to prevent reentrancy no matter the way of refunding.

**Comment by WangSecurity** [comment]
@kennedy1030 still it doesn't change the fact that this issue will only work when the other one is fixed. Hence, it should be invalid based on the rules.
