### ISSUE TITLE
0x486776 - `Edition::_refundExcess` doesn't refund to the buyers.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#190]
0x486776

high

# `Edition::_refundExcess` doesn't refund to the buyers.

## Summary

`Edition::_refundExcess` doesn't refund to the buyers because there are no remaining funds in `Edition.sol`.

## Vulnerability Detail

At `L236` of `Edition::mint`, it calls `FEE_MANAGER.collectMintFee()` and sends the `FEE_MANAGER` all ether paid by the `msg.sender`. As a result, there are no remaining funds in the edition contract, and `_refundExcess()` at `L241` sends no money back to the `msg.sender`.

```solidity
    function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
236     FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );

        _issue(to_, tokenId_, amount_, data_);
241     _refundExcess();
    }
```

This problem also occurs in `Edition::mintWithComment` and `Edition::mintBatch`.

## Impact

Buyers never receive remaining funds.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L242

## Tool used

Manual Review

## Recommendation

The refunding mechanism should be implemented in `FeeManager.sol`, not in `Edition.sol`.

Duplicate of #269

**Comment by sammy-tm** [comment]
Escalate

Dup of #269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Dup of #269 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sammy-tm](https://github.com/sherlock-audit/2024-04-titles-judging/issues/190/#issuecomment-2108039223): accepted
