### ISSUE TITLE
0x486776 - The remaining fee for creation is not sent to the creator of the edition.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#191]
0x486776

high

# The remaining fee for creation is not sent to the creator of the edition.

## Summary

When someone creates a new edition, they pay the creation fee, but the protocol does not refund any remaining ether to them.

## Vulnerability Detail

When someone wants to create a new edition, they call `TitlesCore::createEdition`.

```solidity
    function createEdition(bytes calldata payload_, address referrer_)
        external
        payable
        returns (Edition edition)
    {
        EditionPayload memory payload = abi.decode(payload_.cdDecompress(), (EditionPayload));

        edition = Edition(editionImplementation.clone());

        // wake-disable-next-line reentrancy
        edition.initialize(
            feeManager, graph, payload.work.creator.target, address(this), payload.metadata
        );

        // wake-disable-next-line unchecked-return-value
87      _publish(edition, payload.work, referrer_);

        emit EditionCreated(
            address(edition),
            payload.work.creator.target,
            payload.work.maxSupply,
            payload.work.strategy,
            abi.encode(payload.metadata)
        );
    }
```

At `L87` of `TitlesCore::createEdition`, it invokes `_publish()`.

```solidity
    function _publish(Edition edition_, WorkPayload memory work_, address referrer_)
        internal
        returns (uint256 tokenId)
    {
        // Publish the new Work in the Edition
        // wake-disable-next-line reentrancy
        tokenId = edition_.publish(
            work_.creator.target,
            work_.maxSupply,
            work_.opensAt,
            work_.closesAt,
            work_.attributions,
            work_.strategy,
            work_.metadata
        );

        // Collect the creation fee
        // wake-disable-next-line reentrancy
138     feeManager.collectCreationFee{value: msg.value}(edition_, tokenId, msg.sender);

        // Create the fee route for the new Work
        // wake-disable-next-line reentrancy
        Target memory feeReceiver = feeManager.createRoute(
            edition_, tokenId, _attributionTargets(work_.attributions), referrer_
        );

        // Set the royalty target for the new Work
        // wake-disable-next-line reentrancy
        edition_.setRoyaltyTarget(tokenId, feeReceiver.target);
    }
```

At `L138` of `TitlesCore::_publish`, it calls `feeManager::collectCreationFee` and sends the `feeManager` all ether paid by the creator(`msg.sender`).

```solidity
    function collectCreationFee(IEdition edition_, uint256 tokenId_, address feePayer_)
        external
        payable
    {
        Fee memory fee = getCreationFee();
        if (fee.amount == 0) return;

        _route(fee, Target({target: protocolFeeReceiver, chainId: block.chainid}), feePayer_);
        emit FeeCollected(address(edition_), tokenId_, ETH_ADDRESS, fee.amount, 0);
    }
```

In `feeManager::collectCreationFee`, it pays the creation fee but does not send the remaining ether to the creator(`feePayer_`). So, if the creator pays more money than the creation fee, they lose their remaining funds.

## Impact

If the creator pays more money than the creation fee, they will lose their remaining funds.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L72-L96

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L120-L149

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L166-L175

## Tool used

Manual Review

## Recommendation

`feeManager::collectCreationFee` should refund the remaining ether to the creator.

```diff
    function collectCreationFee(IEdition edition_, uint256 tokenId_, address feePayer_)
        external
        payable
    {
        Fee memory fee = getCreationFee();
        if (fee.amount == 0) return;

        _route(fee, Target({target: protocolFeeReceiver, chainId: block.chainid}), feePayer_);
+       payable(feePayer_).safeTransferETH(address(this).balance);
        emit FeeCollected(address(edition_), tokenId_, ETH_ADDRESS, fee.amount, 0);
    }
```

**Comment by whitehair0330** [comment]
Escalate
Dup of 30

**Comment by sherlock-admin3** [comment]
> Escalate
> Dup of 30

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the escalation. This issue is a duplicate of #269. 
(#30 is dup of #269)

**Comment by WangSecurity** [comment]
Excuse me, I believe this should remain invalid. Creation fee can only be changed by the owner, hence, there are two scenario's this issue may occur:

1. User mistakenly sends more msg.value than creation fee -- user mistake
2. Admin accidentally changes the fee right before the user creates the work -- admins are trusted, hence, this scenario is not viable.

While in situation with mint fee, it's changed with by the work creator, who is not trusted. #30 is also planned to be invalidated.
Planning to reject the escalation, cause it doesn't effect the reward distribution.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [whitehair0330](https://github.com/sherlock-audit/2024-04-titles-judging/issues/191/#issuecomment-2109218047): rejected
