### ISSUE TITLE
0x73696d616f - `owner` of `FeeManager` is set to `TitlesCore`, which can not perform `onlyOwner` functions

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#197]
0x73696d616f

high

# `owner` of `FeeManager` is set to `TitlesCore`, which can not perform `onlyOwner` functions

## Summary

`FeeManager` functionality that relies only on the `owner` can not be performed as `TitlesCore` is its `owner` and is missing the required functions.

## Vulnerability Detail

`FeeManager` is [deployed](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L47) in `TitlesCore::constructor()`. `FeeManager::constructor()` [sets](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L114) the `_initialOwner()` to `msg.sender`, which would be `TitlesCore`, as explained before. Thus, `onlyOwner` functionality will not be reachable as `TitlesCore` is not able to call these functions.

As shown in the [readme](https://audits.sherlock.xyz/contests/326), the ability to grant/revoke roles should be present in the `FeeManager`:
> 3) Grant or revoke any role to/from any address (grantRole, revokeRole).

The readme is slightly incorrect as it says that the `ADMIN_ROLE` is the one that should call upgrade/revoke, but this is not possible to do by the `admin` in the `FeeManager` as these functions are `onlyOwner` in the [OwnableRoles](https://github.com/Vectorized/solady/blob/main/src/auth/OwnableRoles.sol#L202-L210) implementation of Solady.. In `TitlesGraph`, `grantRoles()` and `revokeRoles()` were [overriden](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L158-L178) to allow the `admin` to call these functions, but not in `FeeManager`.

## Impact

Inability to perform `OnlyOwner` functionality in the `FeeManager`, including granting and revoking roles which was stated in the readme as expected.

## Code Snippet

`TitlesCore::initialize()` [instantiating](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L47) the `FeeManager`.
```solidity
function initialize(address feeReceiver_, address splitFactory_) external initializer {
    ...
    feeManager = new FeeManager(msg.sender, feeReceiver_, splitFactory_);
    ...
}
```
`FeeManager::constructor()` [setting](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L114) the `owner` to `msg.sender` (`TitlesCore`).
```solidity
constructor(address admin_, address protocolFeeReceiver_, address splitFactory_) {
    _initializeOwner(msg.sender);
    ...
}
```

## Tool used

Manual Review

## Recommendation

In `FeeManager::constructor()`, set the `owner` to `admin`, which is the address that [calls](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L47) `TitlesCore::initialize()` (the first argument `admin` is set to `msg.sender` in `TitlesCore` when creating `FeeManager`).
```solidity
constructor(address admin_, address protocolFeeReceiver_, address splitFactory_) {
    _initializeOwner(admin_);
    _grantRoles(admin_, ADMIN_ROLE);
    protocolFeeReceiver = protocolFeeReceiver_;
    splitFactory = SplitFactoryV2(splitFactory_);
}
```

Duplicate of #148

**Comment by 0x73696d616f** [comment]
Escalate

This should be a valid issue as TitlesCore is not able to perform ownership functionality as intended.

**Comment by WangSecurity** [comment]
Indeed, the watsons are correct here, planning to accept the escalation and create a new family of medium severity with the core issue of "roles are set incorrectly or not set at all" and duplicate with #148 (also in #148 you can see a more comprehensive list of duplicates).

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #148

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2024-04-titles-judging/issues/197/#issuecomment-2106252048): accepted
