### ISSUE TITLE
ydlee - `mintBatch` always reverts when minting for multiple works, breaking the core contract functionality.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#202]
ydlee

medium

# `mintBatch` always reverts when minting for multiple works, breaking the core contract functionality.

## Summary
`mintBatch` always reverts when minting for multiple works, breaking the core contract functionality.

## Vulnerability Detail
Tokens will be minted for the given works in `Edition.mintBatch`. For each work, mint fees are collected (L287). However, all the paid fees (i.e. `msg.value`) are charged by the first work, leaving no fees for the remaining works. Thus the `FEE_MANAGER.collectMintFee` for the remaining works will revert.
1. In `mintBatch`, minter pays `msg.value` to `Edition` for minting multiple tokens for the given works, so `Edition.balance = msg.value`.
2. For the 1st work, `msg.value` are transfered to `FEE_MANAGER` from `Edition` to collect mint fees, so `Edition.balance = 0`.
3. `FEE_MANAGER.collectMintFee` does not refund excess mint fees to `Edition.balance`, so `Edition.balance = 0` after `FEE_MANAGER.collectMintFee`.
4. For the 2nd work, `Edition` has no balance, thus the `msg.value` sent to `FEE_MANAGER.collectMintFee` is 0, and the `FEE_MANAGER.collectMintFee` will revert.
```solidity
277:    function mintBatch(
278:        address to_,
279:        uint256[] calldata tokenIds_,
280:        uint256[] calldata amounts_,
281:        bytes calldata data_
282:    ) external payable {
283:        for (uint256 i = 0; i < tokenIds_.length; i++) {
284:            Work storage work = works[tokenIds_[i]];
285:
286:            // wake-disable-next-line reentrancy
287:@>          FEE_MANAGER.collectMintFee{value: msg.value}(
288:                this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
289:            );
290:
291:            _checkTime(work.opensAt, work.closesAt);
292:            _updateSupply(work, amounts_[i]);
293:        }
294:
295:        _batchMint(to_, tokenIds_, amounts_, data_);
296:        _refundExcess();
297:    }
```
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L277-L297

## Impact
`mintBatch` does not work as expected when minting for multiple works, breaking the core contract functionality.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L277-L297

## Tool used

Manual Review

## Recommendation
The problem can be solved by:
1. `FeeManager` refunds the excess mint fees to `Edition`, so `Edition` has the ether to pay the mint fees of the next work, or
2. `Edition` sends each work a portion of the mint fee paid by minter, an amount proportional to its mint amount.

Duplicate of #280

**Comment by YD-Lee** [comment]
Escalate

Dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/280

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/280

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #280

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #280

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [YD-Lee](https://github.com/sherlock-audit/2024-04-titles-judging/issues/202/#issuecomment-2110531680): accepted
