### ISSUE TITLE
Yu3H0 - mint function will not refund any funds

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#211]
Yu3H0

high

# mint function will not refund any funds

## Summary
mint function will not refund any funds

## Vulnerability Detail
in ``mint`` ``mintWithComment`` ``mintBatch`` function, it will sends all funds to FEE_MANAGER, but FEE_MANAGER will not give the funds after the fee back to Edition contract.
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228
```solidity
    function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );
        
        _issue(to_, tokenId_, amount_, data_);
        
        _refundExcess();
    }
```
so the funds will be in the FEE_MANAGER contract, if anyone else malicious use a malicious strategy, he will route the money or just use these funds to mint for free.

In the mean time, mintBatch will fail becuase of the for loop without funds back.
```solidity
    function mintBatch(
        address to_,
        uint256[] calldata tokenIds_,
        uint256[] calldata amounts_,
        bytes calldata data_
    ) external payable {
        for (uint256 i = 0; i < tokenIds_.length; i++) {
            Work storage work = works[tokenIds_[i]];

            // wake-disable-next-line reentrancy
            FEE_MANAGER.collectMintFee{value: msg.value}(
                this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
            );

            _checkTime(work.opensAt, work.closesAt);
            _updateSupply(work, amounts_[i]);
        }

        _batchMint(to_, tokenIds_, amounts_, data_);
        _refundExcess();
    }
```

## Impact 
funds loss

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228

## Tool used

Manual Review

## Recommendation
give the monery back to edition contract

Duplicate of #269

**Comment by MageIntern** [comment]
Escalate

It is dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> It is dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/269

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [MageIntern](https://github.com/sherlock-audit/2024-04-titles-judging/issues/211/#issuecomment-2106717532): accepted
