### ISSUE TITLE
fibonacci - TitlesGraph's acknowledge/unacknowledge edge functions are vulnerable to signature malleability

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#228]
fibonacci

high

# TitlesGraph's acknowledge/unacknowledge edge functions are vulnerable to signature malleability

## Summary

Valid signatures could be crafted by a malicious user to replay previously signed messages.

## Vulnerability Detail

A user can acknowledge an edge using an ECDSA signature.
```solidity
function acknowledgeEdge(bytes32 edgeId_, bytes calldata data_, bytes calldata signature_)
    external
    checkSignature(edgeId_, data_, signature_)
    returns (Edge memory edge)
{
    return _setAcknowledged(edgeId_, data_, true);
}
...
function unacknowledgeEdge(bytes32 edgeId_, bytes calldata data_, bytes calldata signature_)
    external
    checkSignature(edgeId_, data_, signature_)
    returns (Edge memory edge)
{
    return _setAcknowledged(edgeId_, data_, false);
}
```
The signed message hash is used to check if previously messages have been processed by the contract.
```solidity
_isUsed[keccak256(signature)] = true;
```

A malicious user can slightly modify the three values _v_, _r_, and _s_ to create other valid signatures. In this case, the signature will be valid, but the hash will be different, allowing the check above to pass. ([Reference](https://swcregistry.io/docs/SWC-117/))

To validate the signature, `TitlesGraph` utilizes `SignatureCheckerLib` by solady, which does not include a check for non-malleability, assuming that the signed message will contain a nonce. ([Reference](https://github.com/Vectorized/solady/issues/524))

However, it is observed that the nonce is not included in the message.

```solidity
bytes32 digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data)));
```

## Impact

The state of acknowledging or unacknowledging an edge can be reset by a malicious user.

Example:
1. A user wishes to acknowledge an edge. To do this, they create a signature (1).
2. The user then changed their mind and decided to unacknowledge the edge. To do this, they create a new signature (2).
3. An attacker can modify the signature created in step 1 and use it to make the edge acknowledged again.
4. If the user repeats their attempt to unacknowledge the edge, the attacker can again invert the state, this time by modifying the signature created in step 2. And so on.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L118-L124
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L146-L152
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L40-L50

## Tool used

Manual Review

## Recommendation

Include the nonce in the signed message.

Duplicate of #279

**Comment by ccashwell** [comment]
This is only possible if the original caller uses a signature with an S-value in the vulnerable range, which no commonly used Ethereum client libs allow. Won't fix.

**Comment by 0xf1b0** [comment]
Escalate

It is a duplicate of issue #279, not #284. Additionally, issue #279 is not a duplicate of issue #273.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> It is a duplicate of issue #279, not #284. Additionally, issue #279 is not a duplicate of issue #273.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #279

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #279

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xf1b0](https://github.com/sherlock-audit/2024-04-titles-judging/issues/228/#issuecomment-2107323041): accepted
