### ISSUE TITLE
Dots - Edition.sol doesn't actually refunt excess ETH

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#245]
Dots

high

# Edition.sol doesn't actually refunt excess ETH

## Summary
`Edition.sol` doesn't actually refunt excess ETH.
## Vulnerability Detail
When minting tokens, all of the ETH gets sent to the `FeeManager` contract, which would leave the `Edition.sol` contract empty to begin with. So any excess ETH would actually get stuck in the `FeeManager` contract. 
## Impact
The user will not recieve his excess ETH back.
## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L242
```Solidity
function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );

        _issue(to_, tokenId_, amount_, data_);
        _refundExcess();
    }
```
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L512-L516
```Solidity
function _refundExcess() internal {
        if (msg.value > 0 && address(this).balance > 0) {
            msg.sender.safeTransferETH(address(this).balance);
        }
    }
```
## Tool used

Manual Review

## Recommendation
Think of a way to return the excess ETH from `FeeManager.sol`.

Duplicate of #269

**Comment by Dots69** [comment]
@Hash01011122 isn't this a dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/269 ?

**Comment by 0xjuaan** [comment]
Escalate

dupe of #269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> dupe of #269 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the escalation. This issue is a duplicate of #269.

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-04-titles-judging/issues/245/#issuecomment-2106537370): accepted
