### ISSUE TITLE
0rpse - Referrers can DoS minting

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#292]
0rpse

medium

# Referrers can DoS minting

## Summary
Every time a new token is minted referrers are sent some ETH, which can lead to reverts and blocking minting.
## Vulnerability Detail
Minting in `Edition.sol` will make a [call](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L236C1-L238C11) to `FeeManager.sol` and fee manager will route protocol fees to referrers using solady's `SafeTransferLib::safeTransferETH`, this will revert if the target reverts. For "mint referrers" users can opt to not include that particular referrer but there exists no way to evade collection referrers which gives collection referrers the ability to revert calls thus blocking every mint of a collection.

## Impact
Collection referrers can block minting of collections they are referred in.
## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L436-L440
https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L463
## Tool used

Manual Review

## Recommendation
Consider adding functionality to change collection referrers or use `forceSafeTransferETH` from SafeTransferLib.

Duplicate of #261

**Comment by 0rpse** [comment]
Escalate

I believe this should be a valid medium as referrers are not trusted.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I believe this should be a valid medium as referrers are not trusted.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Firstly, I agree with the sponsor that there is no incentive, moreover, the referrer loses earning fees if they do that. Secondly, as I understand you can create new collection if without this particular collection referrer. Finally, I believe it doesn't fall into Sherlock's DOS and griefing [rule](https://docs.sherlock.xyz/audits/judging/judging#iii.-sherlocks-standards), cause as I understand it doesn't effect any time sensitive functions and funds are not stoled, since the txn reverts.

**Comment by cvetanovv** [comment]
I agree with the escalation. This issue is a duplicate of #261. The outcome there will decide whether it is valid.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #261

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0rpse](https://github.com/sherlock-audit/2024-04-titles-judging/issues/292/#issuecomment-2107248749): accepted
