### ISSUE TITLE
BiasedMerc - FeeManager::collectCreationFee() doesn't refund leftover ETH after paying fee and there is no way to rescue funds

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#3]
BiasedMerc

high

# FeeManager::collectCreationFee() doesn't refund leftover ETH after paying fee and there is no way to rescue funds

## Summary

When `FeeManager::collectCreationFee()` is called the full `msg.value` is sent to with the call. Once the fees are calculated and transfered, the remaining funds are not returned to the user and `FeeMananger` has no way to rescue funds.

## Vulnerability Detail

When publising a new Edition in `TitleCore` the creator needs to pay a creation fee:

[TitlesCore::_publish()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L120-L138)
```solidity
    function _publish(Edition edition_, WorkPayload memory work_, address referrer_)
        internal
        returns (uint256 tokenId)
    {

...Skip!...

        feeManager.collectCreationFee{value: msg.value}(edition_, tokenId, msg.sender);

```
`feeManager.collectCreationFee{value: msg.value}(edition_, tokenId, msg.sender);` sends the full msg.value of the transaction, however `collectCreationFee` doesn't return the remaining funds after getting the creation fee:

[FeeManager::collectCreationFee()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L166-L175)
```solidity
    function collectCreationFee(IEdition edition_, uint256 tokenId_, address feePayer_)
        external
        payable
    {
        Fee memory fee = getCreationFee();
        if (fee.amount == 0) return;

        _route(fee, Target({target: protocolFeeReceiver, chainId: block.chainid}), feePayer_);
        emit FeeCollected(address(edition_), tokenId_, ETH_ADDRESS, fee.amount, 0);
    }
```
This means that the user will lose their left over fund. `FeeMananger` also has no rescue function meaning any remaining funds will be locked within the contract.

## Impact

Users will lose funds whenever a new Edition will be published, and `FeeMananger` will continue to accumulate funds without being able to withdraw them.

## Code Snippet

[TitlesCore::_publish()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L120-L138)

## Tool used

Manual Review

## Recommendation

Add a refund function similar to [Edition::_refundExcess()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L512-L517) that will be called at the end of the function to ensure any leftover funds will be refunded:
```solidity
    function _refundExcess() internal {
        if (msg.value > 0 && address(this).balance > 0) {
            msg.sender.safeTransferETH(address(this).balance);
        }
    }
```

Duplicate of #112

**Comment by sammy-tm** [comment]
Escalate

Dup of #269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Dup of #269 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
#269 talks about mint fee not returning the excess ETH and #112 talks about creation fee not returning excess ETH. This report is about creation fee, hence, correctly duplicated with #112.

Planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Duplicate of #112

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sammy-tm](https://github.com/sherlock-audit/2024-04-titles-judging/issues/3/#issuecomment-2107309503): rejected
