### ISSUE TITLE
BengalCatBalu - In the `FeeManager.sol::_splitProtocolFee` function, the collectionReffererShare recipient is misspelled.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#326]
BengalCatBalu

high

# In the `FeeManager.sol::_splitProtocolFee` function, the collectionReffererShare recipient is misspelled.

## Summary
When splitting protocolFee between feeReceiver, refferer_ (referral mint),refferers[edition] (referral edition), wrong collectionReferrerShare recipient, refferer_ and refferers[edition] are mixed up

## Vulnerability Detail
When paying the mint fee, a series of function calls (any mint in Edition -> `FeeManager.sol::collectMintFee` -> `FeeManager.sol::_collectMintFee` -> `FeeManager.sol::_collectMintFee` -> `FeeManager.sol::_splitProtocolFee`) reaches _splitProtocolFee, which distributes the protocol fee between the protocol and reffers. 

There are two kinds of refferef - at mint, the one specified directly by the user, e.g. [here](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L232-L232) this refferer in _splitProtocolFee should get mintReferrerShare. There is also a refferer that is specified when creating edition. If the previous one is specified by the user who is minting, this one is saved when the Edition is created in a series of `TitlesCore::createEdition -> ... calls. -> feeManager.createRoute. The saving takes place [here](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L159-L159).

So these are two different refferers 
mintRefferer (the first one) should get 50% percent of protocolFee, as can be understood from [this call](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L420-L420)

editionRefferef on the other hand gets 25% of protocolFee. [Call](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L421-L421)

However, when calling the function [_route](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L436-L436) which simply translates eth to the address of the specified recipient (Target.target), refferrer_ is specified as the recipient, not refferers[edition], that is the first refferer

## Impact
This bug breaks protocol behavior, and also happens absolutely every time any of the mint functions are called (except promoMint, which doesn't pay a commission)

Score: High

## Code Snippet
You can quickly realize the wrong recipient by looking at this snippet
```solidity
function _splitProtocolFee(
        IEdition edition_,
        address asset_,
        uint256 amount_,
        address payer_,
        address referrer_
    ) internal returns (uint256 referrerShare) {
        // The creation and mint referrers earn 25% and 50% of the protocol's share respectively, if applicable
        uint256 mintReferrerShare = getMintReferrerShare(amount_, referrer_); // calculated for refferer_
        uint256 collectionReferrerShare   = getCollectionReferrerShare(amount_, referrers[edition_]); // calculated for refferes[edition]
        referrerShare = mintReferrerShare + collectionReferrerShare;

        _route(
            Fee({asset: asset_, amount: amount_ - referrerShare}),
            Target({target: protocolFeeReceiver, chainId: block.chainid}),
            payer_
        );

        _route(
            Fee({asset: asset_, amount: mintReferrerShare}), 
            Target({target: referrer_, chainId: block.chainid}), // send to refferer_
            payer_
        );

        _route(
            Fee({asset: asset_, amount: collectionReferrerShare}), 
            Target({target: referrer_, chainId: block.chainid}), // send also to refferer_ , not refferers[edition_]
            payer_
        );
```
## Tool used

Manual Review

## Recommendation
Change target to refferer_[edition]

Duplicate of #267

**Comment by vsharma4394** [comment]
Escalate

Duplicate of #267 not #265

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Duplicate of #267 not #265

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #267

**Comment by BengalCatBalu** [comment]
I just want to point out, you plan to accept as duplicate #267 two of my different problems #352

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #267

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [vsharma4394](https://github.com/sherlock-audit/2024-04-titles-judging/issues/326/#issuecomment-2109195407): accepted
