### ISSUE TITLE
0x73696d616f - `SplitV2` wallets created by `splitFactory` ownership are set to `FeeManager` instead of the protocol

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#346]
0x73696d616f

medium

# `SplitV2` wallets created by `splitFactory` ownership are set to `FeeManager` instead of the protocol

## Summary

`SplitV2` wallets created by `splitFactory` are supposed to be owned by the protocol, as mentioned by [this](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L142) comment, but it is not the case.

## Vulnerability Detail

`SplitV2` wallets created by `splitFactory` [have](https://github.com/0xSplits/splits-contracts-monorepo/blob/ad5974a4bad6a454aa46f01f618ac5bb078d1e28/packages/splits-v2/src/splitters/SplitFactoryV2.sol#L68) an `owner` which is set in the `SplitFactory::createSplit()` [call](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L144) in `FeeManager::createRoute()`. The comment in the code indicates that the ownership is intended to be retained by the protocol
> // Create the split. The protocol retains "ownership" to enable future use cases.

However, `FeeManager` is not upgradeable and does not have the functionality to call any `onlyOwner` functions of the created wallet.

## Impact

Ownership of Split wallets is not guaranteed which could comprise future functionality or even funds, as it goes against what the protocol expected.

## Code Snippet

[FeeManager::createRoute()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L125)
```solidity
...
// Create the split. The protocol retains "ownership" to enable future use cases.
receiver = Target({
    target: splitFactory.createSplit(
        SplitV2Lib.Split({
            recipients: targets,
            allocations: revshares,
            totalAllocation: 1e6,
            distributionIncentive: 0
        }),
        address(this),
        creator.target
        ),
    chainId: creator.chainId
});
...
```

## Tool used

Manual Review

Vscode

## Recommendation

The `owner` of the `FeeManager` is `TitlesCore` so the `owner` of the Split wallet can not be set to `owner`. Thus, consider making the `owner` of `FeeManager` the `owner` of `TitlesCore` (as explained in another issue, this would be done in the constructor of `TitlesCore` first. And then, set the `owner` of the Split wallet to `owner()`.

Duplicate of #148

**Comment by 0x73696d616f** [comment]
Escalate

This issue should be valid as it shows how the ownership of the Split Wallets is compromised as their ownership is not retained to the protocol, but to the FeeManager. FeeManager is not even upgradeable so there is nothing it can do.

**Comment by WangSecurity** [comment]
As I understand the only onlyOwner function in Split Wallet is to update the split and even if it's the case and we cannot update the split, then we can make a new one? Please correct me if I'm wrong

**Comment by 0x73696d616f** [comment]
Making a new split will not help as the attributions from works will be linked to the past split (wallet).

**Comment by WangSecurity** [comment]
Thank you for that response, but I believe report fails to show the impact:

> could comprise future functionality or even funds

In the current state, I believe the report is only a recommendation. Hence, planning to reject the escalation and leave the issue as it is.

**Comment by 0x73696d616f** [comment]
Sorry, I don't understand. The impact is the only owner functions and the wallet are compromised. The SplitWallet will not be able to execute transactions and all permissioned wallet functions.

**Comment by 0x73696d616f** [comment]
Could not be more clear, the owner of the wallet is not set.

**Comment by 0x73696d616f** [comment]
The [wallet](https://github.com/0xSplits/splits-contracts-monorepo/blob/ad5974a4bad6a454aa46f01f618ac5bb078d1e28/packages/splits-v2/src/splitters/SplitWalletV2.sol#L19) can:
- [update](https://github.com/0xSplits/splits-contracts-monorepo/blob/ad5974a4bad6a454aa46f01f618ac5bb078d1e28/packages/splits-v2/src/splitters/SplitWalletV2.sol#L115) the split 
- [support](https://github.com/0xSplits/splits-contracts-monorepo/blob/ad5974a4bad6a454aa46f01f618ac5bb078d1e28/packages/splits-v2/src/utils/ERC1271.sol#L12) EIP1271
- [execute](https://github.com/0xSplits/splits-contracts-monorepo/blob/ad5974a4bad6a454aa46f01f618ac5bb078d1e28/packages/splits-v2/src/utils/Wallet.sol#L55) transactions.

All of this will be DoSed as the owner was not set. In any case, not setting the owner of a wallet is a severe vulnerability.

**Comment by 0x73696d616f** [comment]
It's exactly like [this](https://github.com/sherlock-audit/2024-04-titles-judging/issues/182) valid issue but in a different smart contract (the Split Wallet).

**Comment by 0x73696d616f** [comment]
The code has a [comment](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L142) saying they want to be owners of the wallet
> // Create the split. The protocol retains "ownership" to enable future use cases.

This is clearly a severe bug.

**Comment by 0x73696d616f** [comment]
It's not a recommendation.

**Comment by 0x73696d616f** [comment]
Just highlighting that the code clearly intends to retain ownership, as show in the [comment](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L142).
> // Create the split. The protocol retains "ownership" to enable future use cases.

But this is not the case, as explained in the issue.

**Comment by 0x73696d616f** [comment]
[docs](https://docs.sherlock.xyz/audits/judging/judging#iii.-sherlocks-standards):
> If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules.

**Comment by WangSecurity** [comment]
Be careful with the rules, there were changes to the Hierarchy of truth, but they're not applied to this contest cause it started earlier than the changes were made. The docs version for this contest are [here](https://github.com/sherlock-protocol/sherlock-v2-docs/blob/4c718d402a5a6cdf1eb296c0e264a39a9a5aebc2/audits/judging/judging/README.md) And now, all contests have their own Rules Version right above the Total SLOC of the contest [here](https://audits.sherlock.xyz/contests/280).

About the escalation, I agree with it and believe it should be duplicated with #148 with the core issue "roles are set incorrectly or not set at all". Planning to accept the escalation and duplicate with #148.

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #148

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2024-04-titles-judging/issues/346/#issuecomment-2106251543): accepted
