### ISSUE TITLE
jennifer37 - _feeReceivers should be updated when transferWork

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#35]
jennifer37

high

# _feeReceivers should be updated when transferWork

## Summary
`_feeReceivers` is the work's creator. When the work is transferred to another people, the related right should be transferred at the same time.

## Vulnerability Detail
When one publisher publish one work, the publisher will become the `_feeReceivers` or one part of the `_feeReceivers`.
```c
    function createRoute(
        IEdition edition_,
        uint256 tokenId_,
        Target[] calldata attributions_,
        address referrer_
    ) external onlyOwnerOrRoles(ADMIN_ROLE) returns (Target memory receiver) {
        Target memory creator = edition_.node(tokenId_).creator;

        if (attributions_.length == 0) {
            // No attributions, pay the creator directly
            receiver = creator;
        } else {
            // Distribute the fee among the creator and attributions
            (address[] memory targets, uint256[] memory revshares) = _buildSharesAndTargets(
                creator, attributions_, edition_.feeStrategy(tokenId_).revshareBps
            );

            // Create the split. The protocol retains "ownership" to enable future use cases.
            receiver = Target({
                target: splitFactory.createSplit(
                    SplitV2Lib.Split({
                        recipients: targets,
                        allocations: revshares,
                        totalAllocation: 1e6,
                        distributionIncentive: 0
                    }),
                    address(this),
                    creator.target
                    ),
                chainId: creator.chainId
            });
        }
      ...
        _feeReceivers[getRouteId(edition_, tokenId_)] = receiver;
        ......
    }
```

Anyone mints this work, and will pay for some mint fees. `_feeReceivers` will receive one part of the minted fees. 
The work(tokenId) is allowed to transfer via `transferWork()`. In transferWork(), the work will be transferred to the new creator. However, the related `_feeReceivers` does not change. The new creator cannot receive the mint fee.
```c
    function transferWork(address to_, uint256 tokenId_) external {
        Work storage work = works[tokenId_];
        if (msg.sender != work.creator) revert Unauthorized();

        // Transfer the work to the new creator
        work.creator = to_;

        emit WorkTransferred(address(this), tokenId_, to_);
    }
```

## Impact
After the work is transferred via transferWork(), the original creator can still receive mint fees. Some key right of one work's creator is not transferred to the new creator.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L412-L420

## Tool used

Manual Review

## Recommendation
When the work is transferred to the new creator, `_feeReceivers` should be updated on the same time.

Duplicate of #283

**Comment by ccashwell** [comment]
Won't fix, this is expected behavior.
