### ISSUE TITLE
BengalCatBalu - Reduction of the commission for the mint due to a lack of data validation in the _collectMintFee function

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#352]
BengalCatBalu

medium

# Reduction of the commission for the mint due to a lack of data validation in the _collectMintFee function

## Summary
The lack of data validation in the `FeeManager::calculateMintFee` and `FeeManager::_calculateMintFee` functions has been described in detail in this [issue](https://github.com/sherlock-audit/2024-04-titles-BengalCatBalu/issues/4)
Here I would like to focus on a specific edge case, when msg.sender is specified as the referer_

If you specify yourself as a referer, then 50% of the protocolFee will be sent to your address in the `FeeManager::_splitProtocolFee` function, thus you significantly reduce the cost of the commission you pay for the mint.
## Vulnerability Detail
I have described the process of paying commissions in minutes in detail in the other two issues
[first](https://github.com/sherlock-audit/2024-04-titles-BengalCatBalu/issues/3) [second](https://github.com/sherlock-audit/2024-04-titles-BengalCatBalu/issues/4) first Title - `In the FeeManager.sol::_splitProtocolFee function, the collectionReffererShare recipient is misspelled.` second Title - `There is no validation on the FeeManager::collectMintFee function, anyone can call it`
It can be seen from them that the specified refferer_ is not validated in any way and receives 50% of the protocolFee
## Impact
The commission fee is greatly reduced for the user who takes advantage of this last resort. 
Score: medium
## Code Snippet
[_splitProtocolFee function](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L412-L412)
```solidity
function _splitProtocolFee(
        IEdition edition_,
        address asset_,
        uint256 amount_,
        address payer_,
        address referrer_
    ) internal returns (uint256 referrerShare) {
        // The creation and mint referrers earn 25% and 50% of the protocol's share respectively, if applicable
        uint256 mintReferrerShare = getMintReferrerShare(amount_, referrer_);
        uint256 collectionReferrerShare   = getCollectionReferrerShare(amount_, referrers[edition_]);
        referrerShare = mintReferrerShare + collectionReferrerShare;

        _route(
            Fee({asset: asset_, amount: amount_ - referrerShare}),
            Target({target: protocolFeeReceiver, chainId: block.chainid}),
            payer_
        );

        _route(
            Fee({asset: asset_, amount: mintReferrerShare}),
            Target({target: referrer_, chainId: block.chainid}),
            payer_
        );

        _route(
            Fee({asset: asset_, amount: collectionReferrerShare}),
            Target({target: referrer_, chainId: block.chainid}),
            payer_
        );
    }
```
## Tool used

Manual Review

## Recommendation
Add appropriate validation to eliminate this edge case

Duplicate of #405

**Comment by sammy-tm** [comment]
Escalate

**Comment by sherlock-admin3** [comment]
> Escalate

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by BengalCatBalu** [comment]
Here I dealt with the case where the buyer himself is listed as the refferer. _calculateMintFee does not validate this case in any way, although it in turn allows to reduce paid commissions by 50%. (50% goes to the refferer, because it is assumed that the nft is made on his template or something, but there is no way to control that the refferer != msg.sender) I didn't specify this in the report, unfortunately, but it also adds an extra risk of potentially Reentrancy.

I think this is a valid issue, as the problem with unnecessary user power when specifying refferer can lead to a reduced commission. The protocol should automatically calculate the refferer using Graph

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #267

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #267

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sammy-tm](https://github.com/sherlock-audit/2024-04-titles-judging/issues/352/#issuecomment-2107329330): accepted

**Comment by WangSecurity** [comment]
This issue was mistakenly picked as a duplicate for #267 and in fact should be a duplicate of #405. The validity of the issue depends on the escalation outcome of #405
