### ISSUE TITLE
0x73696d616f - Lost funds due to not validating the number of recipients in `FeeManager`, as the `SplitFactory` and `Wallet` do not validate it

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#355]
0x73696d616f

medium

# Lost funds due to not validating the number of recipients in `FeeManager`, as the `SplitFactory` and `Wallet` do not validate it

## Summary

`SplitV2` and `SplitFactory` do not validate the number of recipients, which could lead to creators receiving fees in their Split wallets but never being able to withdraw them due to OOG.

## Vulnerability Detail

`SplitV2` and `SplitFactory` may only revert if the number of recipients is so large that it runs out of gas when verifying if the sum of the individual allocation of the recipients matches the total allocation, [SplitFactoryV2::createSplit()](https://github.com/0xSplits/splits-contracts-monorepo/blob/ad5974a4bad6a454aa46f01f618ac5bb078d1e28/packages/splits-v2/src/splitters/SplitFactoryV2.sol#L66) -> [SplitWalletV2::initialize()](https://github.com/0xSplits/splits-contracts-monorepo/blob/ad5974a4bad6a454aa46f01f618ac5bb078d1e28/packages/splits-v2/src/splitters/SplitWalletV2.sol#L72) -> [SplitV2::validate()](https://github.com/0xSplits/splits-contracts-monorepo/blob/ad5974a4bad6a454aa46f01f618ac5bb078d1e28/packages/splits-v2/src/libraries/SplitV2.sol#L59-L61).

Thus, as distributing assets likely consumes significantly more gas than a simple sum operation, it would likely revert when distributing given enough recipients.

## Impact

Lost funds, stuck in the Split wallets due to running OOG when distributing.

## Code Snippet

The functionality to limit recipients is missing, so no code snippet. Check the links above for the confirmation that the `Split` ecossystem does not validate the number of recipients.

## Tool used

Manual Review

Vscode

## Recommendation

Set an hardcap on the number of recipients (should be different per blockchain). The `Split` docs mention [2000](https://splits.org/help/split-contract/) maximum recipients.

**Comment by 0x73696d616f** [comment]
Escalate

This should be a valid medium issue, the issue shows how it is possible to add to many recipients and make the transaction revert. The underlying integration warns about this in their docs but there is not cap on it.

**Comment by cvetanovv** [comment]
This is invalid. 

If it happens OOG here, the function will be called with a smaller array. I don't see the problem.

Planning to reject the escalation and leave the issue as is.

**Comment by 0x73696d616f** [comment]
This is indeed invalid but for [this](https://github.com/sherlock-audit/2024-04-titles-judging/issues/277#issuecomment-2083195156) reason.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2024-04-titles-judging/issues/355/#issuecomment-2106250988): rejected
