### ISSUE TITLE
0rpse - `collectMintFee` allows users to drain ETH out of `FeeManager.sol`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#357]
0rpse

medium

# `collectMintFee` allows users to drain ETH out of `FeeManager.sol`

## Summary
Users can utilize `collectMintFee` function to withdraw funds from `FeeManager.sol` bypassing `withdraw` function guarded by admin role checks.
## Vulnerability Detail
`FeeManager.sol` has a [withdraw](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L352-L357) function to remove assets from it by the admin. Users can call `collectMintFee` to drain ETH as it is open to anyone to call, bypassing `withdraw` function checks.
## Impact
Users can bypass admin checks to withdraw assets from `FeeManager.sol`.
## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L183-L193
## Tool used

Manual Review

## Recommendation
Consider adding checks to `collectMintFee` so that only contracts that should call them have the ability to call it.

Duplicate of #425

**Comment by 0rpse** [comment]
Escalate

The issue of collectMintFee not having proper access control leading to any user being able to route any asset out of FeeManager should be valid

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> The issue of collectMintFee not having proper access control leading to any user being able to route any asset out of FeeManager should be valid

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the escalation, and this issue is a duplicate of #266.

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #266 

---

actual severity still depends on 266

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0rpse](https://github.com/sherlock-audit/2024-04-titles-judging/issues/357/#issuecomment-2107260549): accepted

**Comment by 0rpse** [comment]
hey @WangSecurity i think you missed this one to duplicate with #425, this was duplicated with #266
this issue mentions ETH so it should be a valid dup of #425

**Comment by WangSecurity** [comment]
@0rpse thank you for notifying, but #425 will be invalid and this issue has to be invalid as well. Look at #425 for more in-depth explanation as it also applies here.
