### ISSUE TITLE
CodeWasp - `Edition.mintBatch(address[], ...)` has disproportionally low mint fee

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#364]
CodeWasp

medium

# `Edition.mintBatch(address[], ...)` has disproportionally low mint fee

## Summary

The mint fee collected by [`Edition.mintBatch(address[], ...)`](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L304-L320) is disproportionally low compared to the number of tokens minted.

## Vulnerability Detail

[`Edition.mintBatch(address[], ...)`](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L304-L320) mints `receivers_.length * amount_`-many tokens, but collects only `amount_ * (strategy_.mintFee + protocolFlatFee)` in mint fees.

## Impact

Disproportionally low mint fees, compared to other minting paths (e.g., [`Edition.mintBatch(address, ...)`](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L277-L297) collects fees proportional to the number of minted tokens).

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L311-L317

## Tool used

Manual Review

## Recommendation

Collect fees proportional to number of tokens minted. Move call to `collectMintFee` into the loop, or call it with `receivers_.length * amount_`.

Duplicate of #264

**Comment by andrey-kuprianov** [comment]
escalate

This is a clear duplicate of #264. Please reconsider the status of this finding.

**Comment by sherlock-admin3** [comment]
> escalate
> 
> This is a clear duplicate of #264. Please reconsider the status of this finding.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by TradMod** [comment]
Escalate

This is a dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/264.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/264. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #264

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #264

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-04-titles-judging/issues/364/#issuecomment-2106845065): accepted
