### ISSUE TITLE
alexzoid - Misuse of Signature for Edge Status Changes

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#367]
alexzoid

medium

# Misuse of Signature for Edge Status Changes

## Summary
 
Signatures can be misused for both acknowledging and unacknowledging an edge in the `TitlesGraph` contract due to inadequate distinction in signature handling.

## Vulnerability Detail

The `acknowledgeEdge` and `unacknowledgeEdge` functions use the same structured data (`ACK_TYPEHASH`) for generating signatures, which lacks an explicit indicator of the intended action (acknowledge or unacknowledge). This oversight allows a signature intended for one action to be valid for the opposite action, causing potential unauthorized status changes.

## Impact

This is a medium severity issue as it allows users to unintentionally change the acknowledgment status of an edge in ways not intended by the signer.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L33-L34

```solidity
bytes32 public constant ACK_TYPEHASH = keccak256("Ack(bytes32 edgeId,bytes data)");
```

## Tool used

Manual Review

## Recommendation

Modify the `ACK_TYPEHASH` to include a boolean flag indicating the intended action:

```solidity
bytes32 public constant ACK_TYPEHASH = keccak256("Ack(bytes32 edgeId, bytes data, bool acknowledged)");

modifier checkSignature(bytes32 edgeId, bytes calldata data, bool acknowledged, bytes calldata signature) {
    bytes32 digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data, acknowledged)));
    ...
}
```

Duplicate of #273

**Comment by alexzoid-eth** [comment]
Escalate

This issue is a valid excluded dup of #273

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue is a valid excluded dup of #273 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #273

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #273

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [alexzoid-eth](https://github.com/sherlock-audit/2024-04-titles-judging/issues/367/#issuecomment-2106669208): accepted
