### ISSUE TITLE
ubl4nk - _refundExcess doesn't work as expected in the protocol

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#37]
ubl4nk

high

# _refundExcess doesn't work as expected in the protocol

## Summary
_refundExcess should refund the excess funds to users, but actually is is not.
## Vulnerability Detail
There are many entries for user in Edition contract to mint a token of a work (`mint`, `mintWithComment`, `mintBatch`, `mintBatch`).
All of them have called the function `_refundExcess` for refunding the user if any excess Ether is sent by user, but actually it is not working as expected by the protocol.
- Alice calls `mint` to issue a token of a work
- We assume the Alice has set 0.1 ETH extra (for example, total mint fee is 0.5 ETH, but Alice has set 0.6 ETH and 0.1 is excess)
```solidity
function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );

        _issue(to_, tokenId_, amount_, data_);
        _refundExcess();
    }
```
- When it reaches to `FEE_MANAGER.collectMintFee`, all the Ethers will be forwarded to the function `collectMintFee` in `FeeManager` contract.
- `_issue` will mint the token for Alice
- When it reaches to `_refundExcess`:
```solidity
function _refundExcess() internal {
        if (msg.value > 0 && address(this).balance > 0) {
            msg.sender.safeTransferETH(address(this).balance);
        }
    }
```
because all the transaction Ethers have been forwarded to `collectMintFee`, so this function doesn't do anything and Alice will lose that 0.1 ETH.
## Impact
_refundExcess is unusable and doesn't work as intended which may lead to loss of funds for users.
## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L228-L242

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L512-L516
## Tool used

Manual Review

## Recommendation
Consider fixing the issue.

Duplicate of #269

**Comment by Alireza-Razavi** [comment]
escalate
This is a valid issue and previously confirmed by the sponsor.
_refundExcess should return the excess funds to caller, but due to a control-flow/work-flow bug it is not doing like this.

**Comment by sherlock-admin3** [comment]
> escalate
> This is a valid issue and previously confirmed by the sponsor.
> _refundExcess should return the excess funds to caller, but due to a control-flow/work-flow bug it is not doing like this.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [alireza-razavi](https://github.com/sherlock-audit/2024-04-titles-judging/issues/37/#issuecomment-2107212849): accepted
