### ISSUE TITLE
smbv-1923 - For Loop would create issue while calling `mintBatch()`

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#374]
smbv-1923

high

# For Loop would create issue while calling `mintBatch()`

## Summary
For Loop would create issue while calling `mintBatch()`
## Vulnerability Detail
- `mintBatch()` is called to Mint multiple tokens for the given works.
- But inside `mintBatch()` for loop has been used for minting muliple tokens which creates error.
- `msg.value` has been passed inside the for loop which creates error.
- Ether has been passed for mint fee's inside the for loop.
- When  `FEE_MANAGER.collectMintFee{value: msg.value}(
                this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
            );` gets called in first iteration at that time all ETH (i.e msg.value) would go into FEE_MANAGER contract .
- In second iteration again the collectMintFee() would get called but this time it would revert as no my ETH has been left.
- It would throw the error of less balance             
## Impact
- mintBatch() would fail everytime due to mxture of for loop and msg.value.
## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L277
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L287
## Tool used

Manual Review

## Recommendation
Don't use msg.value in for loop as create's issue

Duplicate of #280

**Comment by TradMod** [comment]
Escalate

Dup of #280

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Dup of #280 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #280

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #280

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-04-titles-judging/issues/374/#issuecomment-2107226565): accepted
