### ISSUE TITLE
ff - A user can mint a token and get back the referrer share fee

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#39]
ff

medium

# A user can mint a token and get back the referrer share fee

## Summary

When minting a token, the user submits the `referrer` parameter. This address will receive a part of the protocol share fee. A malicious user is able to get back a portion of his payment submitting his address as a `referrer`.

## Vulnerability Detail

Any user who wants to mint a token calling `mintWithComment` or `mint` functions can submit his own address or any controlled address as a `referrer` parameter. When processing the minting request, the protocol fee is splitted within the `_splitProtocolFee` function. 

This way, the malicious user will receive back 50% of the protocolShare.
This amount is actually 75%, this is discussed in another submitted issue.

## Impact

A malicious user is able to illegitimately get back part of the protocol share fee while minting a token.

## Code Snippet

- `mint`and `mintWithComment` function does not check `referrer` paramter

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L234

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L252-L259

- `_splitProtocolFee` sends 50% of the protocol fee to the `referrer`

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L430-L434

## Tool used

Manual Review

## Recommendation

Consider establishing a whitelist of `referrer` upon specific criteria and check that the submitted `referrer` is whitelisted.

Duplicate of #405

**Comment by WangSecurity** [comment]
Firstly, I believe this issue is different from #267. Cause the main report talks about incorrect referrer passed as the collection referrer, while this report is about putting yourself as a referrer and stealing fees from other referrers. Planning to duplicate it with #405 instead.
