### ISSUE TITLE
0x73696d616f - Malicious editions can be created to publish works and perform all sort of attacks

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#394]
0x73696d616f

high

# Malicious editions can be created to publish works and perform all sort of attacks

## Summary

`TitlesCore::publish()` does not validate if the `edition_` argument was created by `TitlesCore`, allowing works to be published through a malicious `Edition`.

## Vulnerability Detail

`TitlesCore::publish()` only validates that `msg.sender` has the `EDITION_PUBLISHER_ROLE` in the `_edition` but does not check if the `_edition` was created by `TitlesCore`. Thus, users may create malicious editions in an attempt to game the protocol or users. For example, they may create a malicious edition that does not charge fees through `FeeManager::collectMintFee()` on `mint`, but sends directly to the `creator` instead, for the loss of the protocol.

## Impact

Loss of revenue for the protocol, spoof attacks for users and credibility.

## Code Snippet

[TitlesCore::publish()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L103) does not validate the `edition_`.
```solidity
function publish(Edition edition_, bytes calldata payload_, address referrer_)
    external
    payable
    returns (uint256 tokenId)
{
    if (!edition_.hasAnyRole(msg.sender, EDITION_PUBLISHER_ROLE)) {
        revert Unauthorized();
    }
    WorkPayload memory payload = abi.decode(payload_.cdDecompress(), (WorkPayload));
    return _publish(edition_, payload, referrer_);
}
```

## Tool used

Manual Review

Vscode

## Recommendation

When creating an edition, set a mapping to true, `_isValidEdition[edition] = true;`.
Then, when publishing works, check if the mapping is set `if (!_isValidEdition[edition_]) revert InvalidEdition()`.

**Comment by 0x73696d616f** [comment]
Escalate

This should be a valid medium issue. Access control is missing and malicious contracts may enter the system. Examples of the impact are clearly stated in the issue.
> For example, they may create a malicious edition that does not charge fees through FeeManager::collectMintFee() on mint, but sends directly to the creator instead, for the loss of the protocol.

> Spoof attacks for users

**Comment by realfugazzi** [comment]
This should be invalid, there is no impact here. 

A malicious edition during publish has no impact as it doesn't alter anything from the core or surrounding contracts. Ultimately users can check if the edition is tied to the core from `createEdition` (also off chain via the event).

**Comment by 0x73696d616f** [comment]
> This should be invalid, there is no impact here.

One example of impact is in the issue

> For example, they may create a malicious edition that does not charge fees through FeeManager::collectMintFee() on mint, but sends directly to the creator instead, for the loss of the protocol.

The next statement is also false

> A malicious edition during publish has no impact as it doesn't alter anything from the core or surrounding contracts. Ultimately users can check if the edition is tied to the core from createEdition (also off chain via the event).

Users interact with editions through `TitlesCore`, as mentioned by the sponsor on discord.
> We are expecting users to interact with Editions through TitlesCore

Thus the argument

> Ultimately users can check if the edition is tied to the core from createEdition (also off chain via the event).

Does not hold and frankly does not matter as by allowing any `_Edition` argument, `TitlesCore` deems it correct to pass in malicious `Edition` implementations. This is not the intent of the sponsor as it was clearly stated on discord. Users are explicitly intended to deploy Editions through `TitlesCore` and use these editions, not malicious ones.

**Comment by realfugazzi** [comment]
But you are assuming a user mistake.

**Comment by ghost** [comment]
Agreed with @realfugazzi this should be invalidated.

**Comment by 0x73696d616f** [comment]
> Ultimately users can check if the edition is tied to the core from createEdition (also off chain via the event).
> But you are assuming a user mistake.

It makes no sense to qualify this as user mistake. Malicious users benefit from malicious editions that, for example, do not charge protocol fees and can offer more competitives prices. It is not user mistake as both the editions creators and the users buying the works may be malicious in this case.

The sponsor message was clear that they intend their users to interact through TitlesCore.

**Comment by ccashwell** [comment]
I believe this is invalid.

The venue for interacting with Edition contracts is the TITLES client. We simply wouldn't index any Edition contracts not deployed directly, so they'd never be surfaced to a user who might mint. This is no different in my opinion than any contract fork as there's no impact to the system itself, only an impact within the localized fork. Furthermore, the worst impact (not counting any socially engineered outcomes, which are out of scope) is loss of protocol fees, and circumventing fees by forking is not a valid issue in the context of this contest.

**Comment by 0x73696d616f** [comment]
> This is no different in my opinion than any contract fork as there's no impact to the system itself, only an impact within the localized fork.

Disagree with this as users are expected to interact with TitlesCore, which they would be doing, but with malicious editions. If the entrypoint wasnt TitlesCore, this would be invalid, but this is not the case.

**Comment by WangSecurity** [comment]
Indeed the malicious actors can create malicious Editions, but as I understand they have to do it themselves, cause `createEdition` only clones the current "official" Edition (implementation), correct? But still the edition can be created and the `TitlesCore::publish` can be used.

Therefore, there will be a separate malicious Edition with works. As an example attack we have that it wouldn't send fee to the protocol. But, for that to happen, the users have to go to a malicious Edition and mint a token on it, correct? Cause as I understand if the users use Titles protocol site, it won't let them mint tokens on malicious Editions and they have to find the malicious edition contract themselves?

Another case is that the publishers will call `TitlesCore::publish` and use the malicious Edition to publish their work, in that case, I believe it's a user mistake if they use the incorrect Edition.

Hence, need clarification on two questions above.

**Comment by sammy-tm** [comment]
I clarified this issue with the sponsor during the contest, so sharing my conversation if in case it helps with the escalation at all : 

![image](https://github.com/sherlock-audit/2024-04-titles-judging/assets/77740870/e4b1a4aa-d0ff-44c1-a458-3168960a9183)

**Comment by WangSecurity** [comment]
With mew information, for this issue to occur, the users have to actually use malicious Editions contract, which would either admin mistake (if the protocol allow for that via Titles UI) or a user mistake (if they find the malicious Edition themselves and use it). Hence, I believe the issue should remain invalid.

Planning ot reject the escalation and leave the issue as it is.

**Comment by 0x73696d616f** [comment]
@WangSecurity it's not user mistake if the users using malicious editions are malicious themselves.

**Comment by WangSecurity** [comment]
By "the users using malicious editions are malicious themselves" you mean malicious users mint works via malicious editions?

**Comment by ccashwell** [comment]
Malicious in the sense that they're avoiding fees by explicitly not participating in the protocol but instead using a fork. Under this logic, every user of a Uniswap fork is also malicious.

**Comment by 0x73696d616f** [comment]
Through TitlesCore

**Comment by 0x73696d616f** [comment]
@ccashwell the entrypoint is TitlesCore, which is a contract of the protocol itself. I accept and respect the HoJ decision.

**Comment by WangSecurity** [comment]
To avoid misunderstanding, I will replace the user with minter, publisher and edition creator. So, we have a malicious edition creator, who makes an Edition NOT through `TitlesCore::Edition`. Then, we have a malicious publisher who creates work via malicious Edition, which allows them to bypass the protocol fee. 

My opinion on it:
Firstly, I agree it may happen. Secondly, still it won't be accessible via original Titles UI and if the malicious edition creator and publisher want minters to come and mint the tokens, they will have to attract minters attention. In that sensem it actually looks like a fork of Titles and a different protocol based on Titles. Moreover, it doesn't pose a threat on the Titles' contracts or users. Yes, I agree that in that way the malicious publisher and malicious edition creator will bypass paying the protocol fee to original Titles, but as I've said, in that sense, malicious Edition and malicious publisher will be more like a standalone project with their own fees and will separate from the original Titles.

Hence, I believe this issue is indeed low severity, planning to reject the escalation and leave the issue as it is.

**Comment by realfugazzi** [comment]
I agree that a validation there could be a good recommendation, but there is no issue because you are factoring user mistake, your report involves tricking the user into using a malicious edition.

As already mentioned, it would be similar to deploying a malicious entire fork of the protocol and tricking anyone into using that.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x73696d616f](https://github.com/sherlock-audit/2024-04-titles-judging/issues/394/#issuecomment-2106250361): rejected
