### ISSUE TITLE
KupiaSec - Absence of Refund Functionality in `FeeManager::collectCreationFee` function

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#399]
KupiaSec

medium

# Absence of Refund Functionality in `FeeManager::collectCreationFee` function

## Summary

The protocol's design requires users to pay a creation fee when attempting to create a new edition. However, if creators inadvertently send an excess amount beyond the required fee, the implementation does not provide a mechanism to refund the overpayment back to the creators.

## Vulnerability Detail

When users initiate the edition creation process by calling the [createEdition](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/TitlesCore.sol#L72) function, the protocol's implementation invokes the [TitlesCore::_publish](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/TitlesCore.sol#L120) function at [L87](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/TitlesCore.sol#L87) handle the publishing logic.

```soldity
TitlesCore.sol
120: function _publish(Edition edition_, WorkPayload memory work_, address referrer_)
121:         internal
122:         returns (uint256 tokenId)
123:     {
124:         // Publish the new Work in the Edition
125:         // wake-disable-next-line reentrancy
126:         tokenId = edition_.publish(
127:             work_.creator.target,
128:             work_.maxSupply,
129:             work_.opensAt,
130:             work_.closesAt,
131:             work_.attributions,
132:             work_.strategy,
133:             work_.metadata
134:         );
135: 
136:         // Collect the creation fee
137:         // wake-disable-next-line reentrancy
138:         feeManager.collectCreationFee{value: msg.value}(edition_, tokenId, msg.sender); //@audit send excess amount here
139: 
140:         // Create the fee route for the new Work
141:         // wake-disable-next-line reentrancy
142:         Target memory feeReceiver = feeManager.createRoute(
143:             edition_, tokenId, _attributionTargets(work_.attributions), referrer_
144:         );
145: 
146:         // Set the royalty target for the new Work
147:         // wake-disable-next-line reentrancy
148:         edition_.setRoyaltyTarget(tokenId, feeReceiver.target);
149:     }

```

At [L138](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/TitlesCore.sol#L138), the implementation directs the creation fee to the `FeeManager` contract by invoking the [FeeManager::collectCreationFee](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L166) function

```soldity
FeeManager.sol
166: function collectCreationFee(IEdition edition_, uint256 tokenId_, address feePayer_)
167:         external
168:         payable
169:     {
170:         Fee memory fee = getCreationFee();
171:         if (fee.amount == 0) return;
172: 
173:         _route(fee, Target({target: protocolFeeReceiver, chainId: block.chainid}), feePayer_);
174:         emit FeeCollected(address(edition_), tokenId_, ETH_ADDRESS, fee.amount, 0);
175:     }

```

The `FeeManager::collectCreationFee` function only collects the required creation fee amount, but does not provide a mechanism to refund any overpayments back to the users.

## Impact

In the event creators inadvertently send more than the required creation fee amount, the implementation does not refund the excess funds, resulting in a loss for the creators.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/TitlesCore.sol#L138

## Tool used

Manual Review

## Recommendation

It is recommended to implement a refund mechanism in the `FeeManager::collectCreationFee` function to return any excess creation fee payments to the creators.

Duplicate of #30

**Comment by KupiaSecAdmin** [comment]
Escalate

This is a duplicate of [#30](https://github.com/sherlock-audit/2024-04-titles-judging/issues/30)

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a duplicate of [#30](https://github.com/sherlock-audit/2024-04-titles-judging/issues/30)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Planning to accept the escalation and duplicate with #269

**Comment by WangSecurity** [comment]
Excuse me, I believe this should remain invalid. Creation fee can only be changed by the owner, hence, there are two scenario's this issue may occur:

1. User mistakenly sends more msg.value than creation fee -- user mistake
2. Admin accidentally changes the fee right before the user creates the work -- admins are trusted, hence, this scenario is not viable.

While in situation with mint fee, it's changed with by the work creator, who is not trusted.

Hence, this issue should be invalid, as well as #30. Planning to reject the escalation.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-04-titles-judging/issues/399/#issuecomment-2106799030): rejected
