### ISSUE TITLE
ff - The collection referrer will never get 25% of the protocol share

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#40]
ff

high

# The collection referrer will never get 25% of the protocol share

## Summary

When a collection is referred, 25% of the protocol share fee should goes to the collection referrer. The current implementation of the code does not comply with this rule. The collection referrer will never get any part of the protocol share.

## Vulnerability Detail

When a user mints a token, the `collectMintFee` function from the `FeeManager` contract is in charge of collecting and dispatching the fees accordingly.

The code's documentation mention that if there is a collection referrer, he should get 25% of the protocol share fee. However if we dig into the `_splitProtocolFee` function which is in charge of doing the splitting of the protocol share fees even though the collection referrer fee is calculated, it is instead sent to the referrer of the mint order.

That means that combined with the fact that a malicious user can specify a controlled address as a referrer; he will receive 75% of the total protocol fees.

## Impact

- The collection referrer will never get any portion of the protocol share.
- A malicious that specifies a controlled address as a referrer will get back 75% of the protocol fees.

## Code Snippet

- The `collectionReferrerShare` is correctly calculated (25% of the total protocol fees)

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L421

- But this amount is sent to the `referrer_` instead of sending it to the `referrers[edition_]` address

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L436-L440

## Tool used

Manual Review

## Recommendation

Change the `target` parameter of the  `_route` function to  `referrers[edition_]` 

Duplicate of #267

**Comment by fatfix** [comment]
Escalate

This is a duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/267.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/267.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by TradMod** [comment]
Escalate

This is a duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/267.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/267.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #267

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #267

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-04-titles-judging/issues/40/#issuecomment-2106869195): accepted
