### ISSUE TITLE
KupiaSec - Lack of Functionality for Granting or Revoking Important Roles in the `Edition` Contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#400]
KupiaSec

medium

# Lack of Functionality for Granting or Revoking Important Roles in the `Edition` Contract

## Summary

The `Edition` contract is designed to include [Edition::grantRoles](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L423) and [Edition::revokeRoles](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L433) functions, which are intended to allow the assignment and revocation of important roles. However, these functions currently lack any implementation, rendering them non-functional and preventing the protocol from properly managing the assigned roles.

## Vulnerability Detail

The [Edition::grantRoles](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L423) and [Edition::revokeRoles](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L433) functions are intended to be restricted to accounts holding the `EDITION_MANAGER_ROLE`.

```soldity
Edition.sol
423: function grantRoles(address user_, uint256 roles_)
424:         public
425:         payable
426:         override
427:         onlyRoles(EDITION_MANAGER_ROLE)
428:     {
429:         _grantRoles(user_, roles_);
430:     }
431: 
432:     /// @inheritdoc OwnableRoles
433:     function revokeRoles(address user_, uint256 roles_)
434:         public
435:         payable
436:         override
437:         onlyRoles(EDITION_MANAGER_ROLE)
438:     {
439:         _removeRoles(user_, roles_);
440:     }
```
Also [Edition::promoMint](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L327) function requires `EDITION_MANAGER_ROLE` or `EDITION_MINTER_ROLE`.

Additionally, the [Edition::promoMint](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L327) function is intended to be restricted to accounts holding either the `EDITION_MANAGER_ROLE` or the `EDITION_MINTER_ROLE`.

```solidity
Edition.sol
327: function promoMint(address[] calldata receivers_, uint256 tokenId_, bytes calldata data_)
328:         external
329:         onlyOwnerOrRoles(EDITION_MANAGER_ROLE | EDITION_MINTER_ROLE)
330:     {
331:         for (uint256 i = 0; i < receivers_.length; i++) {
332:             _issue(receivers_[i], tokenId_, 1, data_);
333:         }
334:     }

```

 `EDITION_MANAGER_ROLE` is only defined within the `TitlesCore` contract, and there is no implementation to call the `Edition::grantRoles` and `Edition::revokeRoles` functions from the `TitlesCore` contract. As a result, the `Edition::grantRoles`, `Edition::revokeRoles`, and `Edition::promoMint` functions are entirely non-functional and  the `EDITION_MINTER_ROLE` cannot be assigned to any accounts.
## Impact

Due to the lack of functionality for granting or revoking the `EDITION_MANAGER_ROLE` and `EDITION_MINTER_ROLE`, the access control requirements for the above three functions cannot be satisfied. As a result, these functions will be unable to be invoked, rendering it non-functional.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L327

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L423

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L433

## Tool used

Manual Review

## Recommendation

It is recommended to review and fix the implementation of the `TitlesCore` contract to ensure that the `Edition::grantRoles`, `Edition::revokeRoles` and `Edition::promoMint` functions can be properly called.

Duplicate of #148

**Comment by ccashwell** [comment]
This is expected, the `EDITION_MANAGER_ROLE` holder (TitlesCore) will be upgraded at a later point to leverage this functionality for a planned feature. In any case, it's not a vulnerability.

**Comment by WangSecurity** [comment]
Agree that it should be duplicated with #148
