### ISSUE TITLE
alexzoid - Broken Refund Mechanism in Edition Contract

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#414]
alexzoid

high

# Broken Refund Mechanism in Edition Contract

## Summary

The `_refundExcess` function in the `Edition` contract does not refund excess `Ether` sent during minting operations, as all funds are collected by the `FEE_MANAGER` before refunds are attempted.

## Vulnerability Detail

In the `Edition` contract, the `_refundExcess` function is designed to return any excess `Ether` to the sender after minting operations. However, this function fails to perform as intended because the `collectMintFee` method in the `FEE_MANAGER` contract collects all Ether sent with the minting transaction prior to the execution of `_refundExcess`. As a result, the contract balance is zero when `_refundExcess` is called, leaving no `Ether` to refund.

## Impact

This is a high severity issue because users who send more `Ether` than required for minting fees will lose it and do not get a refund as expected.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L242

```solidity
    function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );

        _issue(to_, tokenId_, amount_, data_);
        _refundExcess();
    }
```

## Tool used

Manual Review

## Recommendation

Modify the minting functions to calculate the required fee beforehand and only send the necessary amount to the `FEE_MANAGER`. Any excess funds should be left in the contract's balance to be refunded by `_refundExcess`. 

Duplicate of #269

**Comment by alexzoid-eth** [comment]
Escalate

This issue is a valid excluded dup of #269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue is a valid excluded dup of #269 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [alexzoid-eth](https://github.com/sherlock-audit/2024-04-titles-judging/issues/414/#issuecomment-2106662700): accepted
