### ISSUE TITLE
maushish - Lack of proper cross-chain EIP-712 parameters could lead to wrong edges getting acknowledged.

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#415]
maushish

medium

# Lack of proper cross-chain EIP-712 parameters could lead to wrong edges getting acknowledged.

## Summary
In the current implementation of `checkSignature` modifier there is no involvement of `chain-id` , `nonce` parameters due to which malicious actor could replay a signature and either unacknowledge or acknowledge an edge.
## Vulnerability Detail
As clearly mentioned in the `readme` file
![image](https://github.com/sherlock-audit/2024-04-titles-maushish/assets/114429859/9126f6ff-7622-401c-88ba-aedadaded988)
The current implementation of  `checkSignature` follows a modified version of EIP-712
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L40

```solidity
    /// @notice Modified to check the signature for a proxied acknowledgment.
    modifier checkSignature(
        bytes32 edgeId,
        bytes calldata data,
        bytes calldata signature
    ) {
        bytes32 digest = _hashTypedData(
            keccak256(abi.encode(ACK_TYPEHASH, edgeId, data))// message with /x19... prefix
        );
        if (
            !edges[edgeId].to.creator.target.isValidSignatureNowCalldata( digest,signature) || _isUsed[keccak256(signature)]
        ) {
            revert Unauthorized();
        }
        _;
        _isUsed[keccak256(signature)] = true;
    }
```
Because the chain ID is not included in the data, all signatures are also valid when the project is launched on a chain with another chain ID.
Signature without chain-id, nonces are not safe along with the standard specified in EIP 712.
## Impact
Mentioned in the summary.
## Code Snippet
```solidity
    function acknowledgeEdge(
        bytes32 edgeId_,
        bytes calldata data_,
        bytes calldata signature_
    )
        external
        checkSignature(edgeId_, data_, signature_)
        returns (Edge memory edge)
    {
        return _setAcknowledged(edgeId_, data_, true);
    }
```

## Tool used

Manual Review

## Recommendation
Implement the use of `nonce` and `chain-id` in `checkSignature` modifier.

**Comment by ccashwell** [comment]
This is not valid. Indeed, the chainId is being validated as part of the EIP712 domain. 

<img width="581" alt="image" src="https://github.com/sherlock-audit/2024-04-titles-judging/assets/184242/b13771ae-8625-4a18-9c09-a52e53c302e1">
