### ISSUE TITLE
nisedo - Improper Role Validation in `TitlesCore.publish()`

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#423]
nisedo

high

# Improper Role Validation in `TitlesCore.publish()`

## Summary

`TitlesCore.publish()` fails to validate roles correctly, allowing `EDITION_MINTER_ROLE` to publish, contrary to the intended access control that should restrict publishing to `EDITION_PUBLISHER_ROLE` and other authorized roles (Admin, Owner, Manager).

## Vulnerability Detail

`TitlesCore.publish()` is designed for publishing new Works within an Edition, a capability intended to be restricted to `ADMIN_ROLE`, `Owner`, `EDITION_MANAGER_ROLE`, and `EDITION_PUBLISHER_ROLE`.
`The EDITION_MINTER_ROLE` should not have publishing privileges.
However, the `hasAnyRole()` function's current implementation incorrectly permits any role to execute `TitlesCore.publish()`, wrongly including `EDITION_MINTER_ROLE`.
```solidity
    /// @notice Publishes a new Work in the given {Edition} using the given payload.
    /// @param edition_ The {Edition} to publish the Work in.
    /// @param payload_ The compressed payload for publishing the Work. See {WorkPayload}.
    /// @param referrer_ The address of the referrer.
    /// @return tokenId The token ID of the new Work.
    function publish(Edition edition_, bytes calldata payload_, address referrer_)
        external
        payable
        returns (uint256 tokenId)
    {
❌      if (!edition_.hasAnyRole(msg.sender, EDITION_PUBLISHER_ROLE)) {
            revert Unauthorized();
        }
```
```solidity
    /// @dev Returns whether `user` has any of `roles`.
    function hasAnyRole(address user, uint256 roles) public view virtual returns (bool) {
❌      return rolesOf(user) & roles != 0;
    }
```
```solidity
    /// @dev Returns the roles of `user`.
    function rolesOf(address user) public view virtual returns (uint256 roles) {
        /// @solidity memory-safe-assembly
        assembly {
            // Compute the role slot.
            mstore(0x0c, _ROLE_SLOT_SEED)
            mstore(0x00, user)
            // Load the stored value.
            roles := sload(keccak256(0x0c, 0x20))
        }
    }
```

This allows a user with the `EDITION_MINTER_ROLE` to inappropriately publish their own Work, potentially with malicious intent, on an Edition where they lack authorization. This issue is compounded by the fact that once a Work is added to an Edition, it cannot be removed.

## Impact

Unauthorized users can publish Works on Editions, breaking core protocol integrity and functionality.

## Code Snippet

- https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/TitlesCore.sol#L98-L110
- https://github.com/Vectorized/solady/blob/a34977e56cc1437b7ac07e6356261d2b303da686/src/auth/OwnableRoles.sol#L234-L237
- https://github.com/Vectorized/solady/blob/a34977e56cc1437b7ac07e6356261d2b303da686/src/auth/OwnableRoles.sol#L222-L232

## Tool used

Manual Review

## Recommendation

Replace the `hasAnyRole()` check by `onlyRoles()` with the correct roles to enforce appropriate access controls.

**Comment by nisedo** [comment]
Escalate

This should be valid
