### ISSUE TITLE
ff - `mintBatch` minting function will always revert

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#43]
ff

medium

# `mintBatch` minting function will always revert

## Summary

The first `mintBatch` function, which is meant to mint multiple tokens for a given work, will always revert.

## Vulnerability Detail

The `Edition` contract is not supposed to hold `ETH` in its balance. After a minting, the excess of funds is sent back to the user via the `_refundExcess` function.

The `mintBatch` function iterates through all the tokensIds to call the `collectMintFee` function.
However a value of the total `msg.value` is sent along the `collectMintFee` function for each iteration of the loop. As the contract does not hold funds, the execution will revert during the second iteration for trying to send over the current balance of the contract. 

In fact, the `msg.value` amount is not updated in the context of the execution of a transaction.

## Impact

 The `mintBatch` functionality will never work as is.

## Code Snippet

- The `mintBatch` function sends `msg.value` each iteration of the loop along the call to `collectMintFee` function

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L277-L289

## Tool used

Manual Review

## Recommendation

Total minting fees for each `tokenId` should be calculated beforehand.
Then the specific `value` should be sent to the `collectMintFee` function.

Duplicate of #280

**Comment by fatfix** [comment]
Escalate

This is a duplicate of #280.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a duplicate of #280. 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by TradMod** [comment]
Escalate

This is a duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/280

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a duplicate of https://github.com/sherlock-audit/2024-04-titles-judging/issues/280

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #280

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #280

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-04-titles-judging/issues/43/#issuecomment-2106867463): accepted
