### ISSUE TITLE
ZdravkoHr. - `FeeManager.collectMintFee` may be used to steal tokens

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#432]
ZdravkoHr.

medium

# `FeeManager.collectMintFee` may be used to steal tokens

## Summary
[FeeManager.collectMintFee()](https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L183-L193) can be called by anyone. This can be used to steal ERC20 tokens from contracts that have approved the FeeManager in future integrations.

## Vulnerability Detail
Even if the contracts do not use ERC20 now, a fee strategy with erc20 asset may be added.
```solidity
        strategy = Strategy({
            asset: strategy_.asset == address(0) ? ETH_ADDRESS : strategy_.asset,
            mintFee: strategy_.mintFee,
            revshareBps: revshareBps,
            royaltyBps: royaltyBps
        });
```
`collectMinFee` can be called by anyone with arbitrary arguments.
```solidity
    function collectMintFee(
        IEdition edition_,
        uint256 tokenId_,
        uint256 amount_,
        address payer_,
        address referrer_
    ) external payable {
        _collectMintFee(
            edition_, tokenId_, amount_, payer_, referrer_, getMintFee(edition_, tokenId_, amount_)
        );
    }
```

An attacker can pass an extremely large number as `amount` to make the internal `_collectMintFee` send assets. Then a mint referral share will be calculated with this large amount and since the function is public, `referrer_` can be any arbitrary address.
```solidity
        uint256 mintReferrerShare = getMintReferrerShare(amount_, referrer_);
```

Then fees will be `routed` using the `_transfer` function. Here a call with `safeTransferFrom` is made. Which means that attacker can steal funds from any contract that has given an approval to the `FeeManager`.
```solidity
    function _transfer(address asset_, uint256 amount_, address from_, address to_) internal {
        if (asset_ == ETH_ADDRESS) {
            to_.safeTransferETH(amount_);
        } else {
            asset_.safeTransferFrom(from_, to_, amount_);
        }
    }
```

## Impact
Stealing funds from contracts approving the FeeManager. This issue arises from the assumption that the collect function will be called by the `Edition` contracts only.  As the contest readme states, `potential issues, like broken assumptions about function behavior, even if they might not be an issue in the context of the scope`,  but may pose a risk in the future should be reported.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L336C1-L341C12

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/fees/FeeManager.sol#L183C1-L193C6

## Tool used

Manual Review

## Recommendation
Add access control to all the functions that collect fees.

**Comment by ZdravkoHr** [comment]
Escalate 

A duplicate of #251

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> A duplicate of #251 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
If the escalation on #251 is rejected, planning to duplicate accordingly. If #251 is accepted and invalidated, this escalation will be invalid as well, since it doesn't effect rewards distribution.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique
--

accepting as 251 was valid at the time the escalation was created

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZdravkoHr](https://github.com/sherlock-audit/2024-04-titles-judging/issues/432/#issuecomment-2106322204): accepted
