### ISSUE TITLE
den_sosnovskyi - `Edition::mintWithComment` should emit author of the work, not receiver of the token

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#436]
den_sosnovskyi

medium

# `Edition::mintWithComment` should emit author of the work, not receiver of the token

## Summary
`Edition::mintWithComment` emits `to_` as an author of the work, but `to_` is a token receiver

## Vulnerability Detail
`Edition::mintWithComment` Comment emission is read off-chain. Its 3rd argument should be the author, not the token receiver. It seems that msg.sender is a work's author, thus it should emit `msg.sender` as an author

## Impact
Not correct emit information about Comment

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L269
```solidity
        emit Comment(address(this), tokenId_, to_, comment_);
```

## Tool used

Manual Review

## Recommendation
```diff
-        emit Comment(address(this), tokenId_, to_, comment_);
+        emit Comment(address(this), tokenId_, msg.sender, comment_);
```

**Comment by ccashwell** [comment]
Because this is intended to support calling via relayers and other indirect methods, this is expected behavior.
