### ISSUE TITLE
alexzoid - Inflexibility in `ADMIN_ROLE` Address Configuration in FeeManager Contract

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#437]
alexzoid

medium

# Inflexibility in `ADMIN_ROLE` Address Configuration in FeeManager Contract

## Summary

The `FeeManager` contract lacks the functionality to update the address associated with the `ADMIN_ROLE`, unlike other contracts in the system such as `TitlesCore` and `TitlesGraph`. 

## Vulnerability Detail

The `FeeManager` contract initializes the `ADMIN_ROLE` with a specific address and does not provide a mechanism to update or change this address, contrasting with other system contracts that allow such modifications. This inconsistency can responsiveness to changes in governance or operational needs.

## Impact

This is a medium severity issue as it restricts the system's ability to respond to changes in administration or to security incidents involving the keys or accounts associated with the `ADMIN_ROLE`. 

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L113-L118

```solidity
    constructor(address admin_, address protocolFeeReceiver_, address splitFactory_) {
        _initializeOwner(msg.sender);
        _grantRoles(admin_, ADMIN_ROLE);
        protocolFeeReceiver = protocolFeeReceiver_;
        splitFactory = SplitFactoryV2(splitFactory_);
    }
```

## Tool used

Manual Review

## Recommendation

To enhance the flexibility and security of the `FeeManager` contract, implement a method to update the `ADMIN_ROLE` dynamically.

**Comment by alexzoid-eth** [comment]
Escalate

This issue is of medium severity. Here's the user flow that highlights the problem:

1. `TitlesCore.initialize()` sets `owner` as `msg.sender` and assigns the `FeeManager`'s `ADMIN` role to `msg.sender`.
2. Ownership is then transferred via `TitlesCore.transferOwnership()`.
3. However, the `ADMIN` role in `FeeManager` cannot be reassigned. Consequently, functions like `FeeManager.setProtocolFees()` and `FeeManager.withdraw()` become inaccessible.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This issue is of medium severity. Here's the user flow that highlights the problem:
> 
> 1. `TitlesCore.initialize()` sets `owner` as `msg.sender` and assigns the `FeeManager`'s `ADMIN` role to `msg.sender`.
> 2. Ownership is then transferred via `TitlesCore.transferOwnership()`.
> 3. However, the `ADMIN` role in `FeeManager` cannot be reassigned. Consequently, functions like `FeeManager.setProtocolFees()` and `FeeManager.withdraw()` become inaccessible.
> 
> 
> 
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
While this is viable, I believe it's only a recommendation to make implement transferability of the Admin Role. Moreover, the role itself is still accessable and still can be used. Planning to reject the escalation and leave the issue as it is.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [alexzoid-eth](https://github.com/sherlock-audit/2024-04-titles-judging/issues/437/#issuecomment-2106776393): rejected
