### ISSUE TITLE
y4y - One of the `Edition.mintBatch` function will always revert

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#45]
y4y

medium

# One of the `Edition.mintBatch` function will always revert

## Summary
The [`mintBatch`](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L277) will always revert and making the function unavailable.

## Vulnerability Detail
As its name suggests, `mintBatch` can mint multiple tokens at once. There are two such functions, and the vulnerable one mints multiple works to the same address:

```solidity
    function mintBatch(
        address to_,
        uint256[] calldata tokenIds_,
        uint256[] calldata amounts_,
        bytes calldata data_
    ) external payable {
        for (uint256 i = 0; i < tokenIds_.length; i++) {
            Work storage work = works[tokenIds_[i]];

            // wake-disable-next-line reentrancy
            FEE_MANAGER.collectMintFee{value: msg.value}(
                this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
            );

            _checkTime(work.opensAt, work.closesAt);
            _updateSupply(work, amounts_[i]);
        }

        _batchMint(to_, tokenIds_, amounts_, data_);
        _refundExcess();
    }
```

The function is payable, and it loops through the tokenIds list, and call `FEE_MANAGER.collectMintFee` in each loop. The problem lies here. It uses `msg.value` for each function call, but since `msg.value` is only sent once with this exact function call, there will be no extra Ethers left for another calls. In all those functions, at the end, there are `_refundExcess` function which makes sure all Ethers in the contract will be refunded to whoever sends the excessive Ethers, so we can assume most of the time, the balance of this contract will be 0. The lack of Ethers will cause this function revert each time on call, and completely useless.

One example would be, Bob wants to mint 2 works from 2 distinct token IDs, so Bob calls `mintBatch` with 0.1 Ethers as value. `mintBatch` gets called, and loops through the 2 token IDs, and tries to call `FEE_MANAGER.collectMintFee` with 0.1 Ethers being the vaule for twice. But Bob only paid 0.1 Ethers, and the current balance of contract is also that, so in the second call, the transaction will revert because no funds left.

## Impact
`mintBatch` function is completely useless.

## Code Snippet
```solidity
    function mintBatch(
        address to_,
        uint256[] calldata tokenIds_,
        uint256[] calldata amounts_,
        bytes calldata data_
    ) external payable {
        for (uint256 i = 0; i < tokenIds_.length; i++) {
            Work storage work = works[tokenIds_[i]];

            // wake-disable-next-line reentrancy
            FEE_MANAGER.collectMintFee{value: msg.value}(
                this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
            );

            _checkTime(work.opensAt, work.closesAt);
            _updateSupply(work, amounts_[i]);
        }

        _batchMint(to_, tokenIds_, amounts_, data_);
        _refundExcess();
    }
```

## Tool used

Manual Review

## Recommendation
Use `FeeManager.getMintFee` for exact amount of fees needed for each mint, and use the value in the loop for mint, and return the excessive ones at the end.

Duplicate of #280

**Comment by sammy-tm** [comment]
Escalate

Dup of #280 not #264

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Dup of #280 not #264 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #280

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #280

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sammy-tm](https://github.com/sherlock-audit/2024-04-titles-judging/issues/45/#issuecomment-2106972939): accepted
