### ISSUE TITLE
juan - Signature malleability- anyone can acknowledge or unacknowledge an edge from someone else's node

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#53]
juan

high

# Signature malleability- anyone can acknowledge or unacknowledge an edge from someone else's node

## Summary
The signatures used within the `TitlesGraph` contract are malleable. This allows a malicious actor to craft a different signature which recovers to the same signer address, allowing the malicious actor to call `acknowledgeEdge()` or `unacknowledgeEdge()` when not intended by the actual signer.

## Vulnerability Detail
The library being used to check signatures is `SignatureCheckerLib` from solady. The following warnings are provided:

```solidity
/// WARNING! Do NOT use signatures as unique identifiers:
                                     ...
/// This implementation does NOT check if a signature is non-malleable.
```
> Permalink [here](https://github.com/Vectorized/solady/blob/58362f785c90c6693e44f358fac594b0851bb357/src/utils/SignatureCheckerLib.sol#L23)

Since the library does not check that a signature is non-malleable, a malicious actor can forge an alternate signature that still resolves to the original signer. 

This would allow them to bypass the uniqueness checks used in the `checkSignature()` modifier, and be able to call `acknowledgeEdge()` or `unacknowledgeEdge()` on their own terms, unintended by the actual signer.

## Impact
Anybody can `acknowledgeEdge` or `unacknowledgeEdge` even though they are not the target address of the `from` node. 

## Code Snippet
**CheckSignature() modifier:** https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/graph/TitlesGraph.sol#L40-L50

**Warning from library:** https://github.com/Vectorized/solady/blob/58362f785c90c6693e44f358fac594b0851bb357/src/utils/SignatureCheckerLib.sol#L23

## Tool used
Manual Review

## Recommendation
**There are 2 options:** Either require a nonce for each signature, or use OpenZeppelin's ECDSA library to safeguard against signature malleability attacks.

Duplicate of #279

**Comment by 0xjuaan** [comment]
Escalate

This is not a dupe of #273 since even if the root cause of that issue is fixed (same sig being used for 2 different functions), this vulnerability is not mitigated against.

Even if the two functions now use a different signature digest, the individual signatures are still vulnerable to malleability, allowing an attacker to craft a different signature that resolves to the same address. This crafted signature can be reused by an attacker to call `acknowledgeEdge()` or `unacknowledgeEdge()`

This applies to all submissions related to signature malleability in `acknowledgeEdge()` and `unacknowledgeEdge()

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is not a dupe of #273 since even if the root cause of that issue is fixed (same sig being used for 2 different functions), this vulnerability is not mitigated against.
> 
> Even if the two functions now use a different signature digest, the individual signatures are still vulnerable to malleability, allowing an attacker to craft a different signature that resolves to the same address. This crafted signature can be reused by an attacker to call `acknowledgeEdge()` or `unacknowledgeEdge()`
> 
> This applies to all submissions related to signature malleability in `acknowledgeEdge()` and `unacknowledgeEdge()

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #279

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #279

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-04-titles-judging/issues/53/#issuecomment-2106267973): accepted
