### ISSUE TITLE
mt030d - `Edition.transferWork()` does not update the fee receiver for the work, preventing the new owner from receiving relevant fees

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#56]
mt030d

medium

# `Edition.transferWork()` does not update the fee receiver for the work, preventing the new owner from receiving relevant fees

## Summary
`Edition.transferWork()` does not update the fee receiver of the work. The relevant fee is sent to the previous owner of the work, but it should be forwarded to the new owner.

## Vulnerability Detail
```solidity
    function transferWork(address to_, uint256 tokenId_) external {
        Work storage work = works[tokenId_];
        if (msg.sender != work.creator) revert Unauthorized();

        // Transfer the work to the new creator
        work.creator = to_;

        emit WorkTransferred(address(this), tokenId_, to_);
    }
```
The creator of a `work` can use the `transferWork()` function from the `Edition` contract to transfer the ownership of the work to a new address. However, the `transferWork()` function does not update the fee receiver of this work. 

```solidity
    mapping(bytes32 id => Target receiver) private _feeReceivers;
```
The ﻿`FeeManager` contract maintains a `﻿_feeReceivers` mapping that stores the fee receivers for each work. When a work is published, its fee receiver is set to the creator or a split wallet if there are attributions. When the ownership of the work changes, the fee receiver should be updated accordingly, but this is not done in the ﻿`transferWork()` function.

## Impact
`Edition.transferWork()` does not update the fee receiver. The relevant fee is sent to the previous owner of the work, but it should be forwarded to the new owner.

## Code Snippet
- https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L412-L420

- https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/fees/FeeManager.sol#L108
 
## Tool used

Manual Review

## Recommendation
In my opinion, I don't see the necessity for the ﻿transferWork() function, so I recommend removing it.
If the ﻿transferWork() function is necessary, consider updating the relevant fee receiver within it.

Duplicate of #283

**Comment by ccashwell** [comment]
Won't fix, this is expected behavior
