### ISSUE TITLE
juan - FeeManager withdrawal mechanism will revert due to insufficient approval, leading to stuck funds

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#6]
juan

high

# FeeManager withdrawal mechanism will revert due to insufficient approval, leading to stuck funds

## Summary
`FeeManager.withdraw()` is a function that is to be used to collect funds that are stuck in the `FeeManager` contract.

The contest README states:
> The current version supports native ETH and any standard ERC20 tokens.

However due to the incorrect usage of `safeTransferFrom`, tokens will not be able to be withdrawn via `FeeManager.withdraw()`, leading to loss of funds for the protocol/users.

## Vulnerability Detail
When the owner/admin calls `FeeManager.withdraw()`, they can specify the `address asset` that they want to withdraw from the FeeManager. 

If this address is not ETH, the internal `_transfer` function does the following:
```solidity
asset_.safeTransferFrom(from_, to_, amount_);
```

However, the `_transfer(address asset_, uint256 amount_, address from_, address to_)`  function was called with the following params:
```solidity
_transfer(asset_, amount_, address(this), to_);
```
Note that the `from_` address is `address(this)`. This means that when the `safeTransferFrom` call is made, it will revert due to insufficient allowance since the contract didn't approve itself to spend the tokens. This is a feature of standard ERC20 tokens, as shown:

```solidity
function transferFrom(address from, address to, uint256 value) public virtual returns (bool) {
        address spender = _msgSender();
        _spendAllowance(from, spender, value);
        _transfer(from, to, value);
        return true;
}
```
The `_spendAllowance` function would revert since the allowance from `address(this)` to itself is `0`.
    
## Impact
The funds will not be able to be withdrawn via `FeeManager.withdraw()`, leading to loss of funds for the protocol/users.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/fees/FeeManager.sol#L465

## Tool used

Manual Review

## Recommendation
Within `FeeManager::_transfer()`, consider using `safeTransfer` instead of `safeTransferFrom` when the `from_` address is `address(this`.
```diff
function _transfer(address asset_, uint256 amount_, address from_, address to_) internal {
        if (asset_ == ETH_ADDRESS) {
            to_.safeTransferETH(amount_);
        } else {
+            if (from_ == address(this)) {
+                asset_.safeTransfer(to_, amount_);
+            }
+           else { 
                asset_.safeTransferFrom(from_, to_, amount_);
+            }
        }
    }
```

**Comment by ccashwell** [comment]
Only ETH is supported as per the contest Q&A. Won't fix.
