### ISSUE TITLE
juan - A user can bypass all fees for publishing and minting due to an edge case

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#60]
juan

medium

# A user can bypass all fees for publishing and minting due to an edge case

## Summary
See detail. 

## Vulnerability Detail
Since the functions `TitlesCore.publish()`, `Edition.mint()`, `Edition.mintBatch()` do not explicitly enforce the fee to be provided in `msg.value`, it assumes that the call would revert within `FeeManager.collectMintFee` and `FeeManager.collectCreationFee` due to insufficient eth when routing the funds to the fee recipient. 

However, the documentation in the `FeeManager` contract clearly states that there is a possibility for ether to be stuck in the `FeeManager` contract:
```solidity
/// @notice An escape hatch to transfer any trapped assets from the contract to the given address.
```
Due to this, calling `TitlesCore.publish()` and the other functions will not revert even though `msg.value == 0`, since the `FeeManager` has residual funds which would be paid to the fee recipient, allowing the current user to not provide the fee along with their call to the stated functions.

## Impact
Users can publish titles and mint editions with 0 fee, so they can mint unlimited editions with no additional cost which breaks core protocol functionality.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/TitlesCore.sol#L120-L149

## Tool used
Manual Review

## Recommendation
Explicitly enforce the payment of fees, by checking that `msg.value == feeRequired` and reverting if that is not the case.

**Comment by 0xjuaan** [comment]
Escalate

The [code comment provided](https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/fees/FeeManager.sol#L347) clearly shows that the protocol considers the possibility for ether to be stuck in the `FeeManager`. 


As a result, users can publish titles and mint editions with 0 fee, by simply draining the value from the `FeeManager` (as explained in the submission).

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> The [code comment provided](https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/fees/FeeManager.sol#L347) clearly shows that the protocol considers the possibility for ether to be stuck in the `FeeManager`. 
> 
> 
> As a result, users can publish titles and mint editions with 0 fee, by simply draining the value from the `FeeManager` (as explained in the submission).

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ghost** [comment]
Root cause of issue:
>the functions TitlesCore.publish(), Edition.mint(), Edition.mintBatch() do not explicitly enforce the fee to be provided in msg.value, it assumes that the call would revert within FeeManager.collectMintFee and FeeManager.collectCreationFee due to insufficient eth when routing the funds to the fee recipient.

Isn't this a design choice. Because **_Readme_** file clearly states
>Are there any hardcoded values that you intend to change before (some) deployments?
>The exact amounts of the fees controlled by FeeManager may change before deployment, but only within the bounds of the current fee constants.
> Fund Management: We chose to delegate fee payouts to 0xSplits v2. The protocol aims to avoid any direct TVL in this release.

@0xjuaan

**Comment by 0xjuaan** [comment]
Based on that excerpt of the README, the *aim* is to avoid any TVL. 
However, as demonstrated in the code (and the comment), they still have an escape hatch to collect ETH from the `FeeManager`. 

This means that the protocol **does** consider the case where ether can end up accumulating in the `FeeManager`. 
When this case occurs, users can bypass all fees for publishing and minting since they can simply provide no `msg.value` and let the accumulated ether pay the fee. 

I believe this makes the issue a valid medium, since the pre-state required for the vulnerability (ETH accumulating in `FeeManager`) is a state that is clearly considered to be possible by the protocol. 

@Hash01011122

**Comment by ghost** [comment]
Would you mind to elaborate upon 
>However, as demonstrated in the code (and the comment), they still have an escape hatch to collect ether from the FeeManager.

**Comment by 0xjuaan** [comment]
https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/fees/FeeManager.sol#L347-L357

In the above code snippet, you can see that there is a function that is intended to collect ether that was stored in the `FeeManager`. This suggests that the protocol expects ether can get accumulated in the `FeeManager`.

@Hash01011122

**Comment by 0xjuaan** [comment]
@Hash01011122 another valid submission of the same vulnerability is #426

**Comment by WangSecurity** [comment]
@0xjuaan to clarify, as I understand the FeeManager isn't intended to hold any ETH and it can only happen if previous minter/publisher sends to much `msg.value` and the excess fee is trappen in FeeManager or users send it directly. If there are other ways, could you please share if there are other ways the funds are inside the FeeManager or not, as cause I understand during the mint function or publish function, we call `collectMintFee` and `collectCreatioFee`, respectively, and non-excess ETH is sent to the fee recepients?

**Comment by WangSecurity** [comment]
After reviewing the report, I'm making the following remarks:

FeeManager is not intended to hold any funds, cause all the fees are distributed and not kept inside the contract. Hence, there are only two ways which can lead to ETH being stored in FeeManager:

Direct transfer -- user mistake.
Vulnerability in https://github.com/sherlock-audit/2024-04-titles-judging/issues/269.
This report doesn't explain the problem of sending the entire msg.value during minting, hence, the only way for an attack in this report to occur is if there was a direct transfer of ETH into the contract, which is the user mistake.

Therefore, planning to reject the escalation and leave the issue as it is.

**Comment by 0xjuaan** [comment]
@WangSecurity fair enough, thanks for the review, won't escalate it more 👍 

hope the devs fix it though

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-04-titles-judging/issues/60/#issuecomment-2111468913): rejected
