### ISSUE TITLE
merlinboii - Excess Funds Not Returned to Sender as Intended in Minting Process

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#63]
merlinboii

medium

# Excess Funds Not Returned to Sender as Intended in Minting Process

## Summary
The [`Edition::_refundExcess()`](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L512-L516) does not refund overpayment after minting tokens to the `msg.sender` as intended, despite the specified behavior at [Edition::L511](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L511). This issue occurs because the entire `msg.value` sent during minting is transferred to the `FeeManager` contract, with any remaining ETH getting locked there after all fees are collected, instead of being refunded by the `Edition` contract.

Furthermore, the `FeeManager` contract lacks the logic to handle refunds to individual senders. Although it has a `withdraw` function, it does not track refund information for each sender, leaving any excess ETH locked within the `FeeManager` contract after all fees are collected.

The functions affected by this error are listed below:
* `Edition` contract
  * [mint()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L242)
  * [mintWithComment()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L252-L270)
  * [mintBatch()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L277-L297)
  * [overloaded-mintBatch()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L304-L320)

## Vulnerability Detail
As mentioned earlier, all `msg.value` sent when minting via the `Edition` contract is transferred to the `FeeManager` contract. However, there is no logic to return the remaining funds back to the `Edition` contract.

As a result, any leftover `msg.value` remains in the `FeeManager` contract instead of being returned to the `sender` and/or `Edition` contract, with no mechanism to refund these remaining funds to the `msg.sender`.

For example, the flow of funds would be as follows:

Using [Edition::mint()](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L228-L242) as an example: 
```md
Assuming that `Edition` and `FeeManager` balances = 0
`sender` -- `msg.value` -> Edition::mint()
                            |--> FEE_MANAGER.collectMintFee{value: msg.value}(...)
                                    |--> (FEE_MANAGER).balance = msg.value
                                        |-> {..SPLIT Fee..}
                                    |--> (Edition).balance = 0
```

```solidity
//File: Edition.sol

228:    function mint(
229:        address to_,
230:        uint256 tokenId_,
231:        uint256 amount_,
232:        address referrer_,
233:        bytes calldata data_
234:    ) external payable override {
235:        // wake-disable-next-line reentrancy
--> 236:        FEE_MANAGER.collectMintFee{value: msg.value}(
237:            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
238:        );
239:
240:        _issue(to_, tokenId_, amount_, data_);
241:        _refundExcess();
242:    }

// SNIPPED

510:    /// @notice Refund any excess ETH sent to the contract.
511:    /// @dev This function is called after minting tokens to refund any ETH left in the contract after all fees have been collected.
512:    function _refundExcess() internal {
513:        if (msg.value > 0 && address(this).balance > 0) {
514:            msg.sender.safeTransferETH(address(this).balance);
515:        }
516:    }
```

## Impact
The sender/minter does not receive the refund as intended design (follows by the implementation of [`Edition::_refundExcess()`](https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L512-L516))

## Code Snippet
```solidity
//File: Edition.sol

228:    function mint(
229:        address to_,
230:        uint256 tokenId_,
231:        uint256 amount_,
232:        address referrer_,
233:        bytes calldata data_
234:    ) external payable override {
235:        // wake-disable-next-line reentrancy
--> 236:        FEE_MANAGER.collectMintFee{value: msg.value}(
237:            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
238:        );
239:
240:        _issue(to_, tokenId_, amount_, data_);
241:        _refundExcess();
242:    }

// SNIPPED

510:    /// @notice Refund any excess ETH sent to the contract.
511:    /// @dev This function is called after minting tokens to refund any ETH left in the contract after all fees have been collected.
512:    function _refundExcess() internal {
513:        if (msg.value > 0 && address(this).balance > 0) {
514:            msg.sender.safeTransferETH(address(this).balance);
515:        }
516:    }
```

## Tool used
Manual Review

## Recommendation
Implement logic in the `FeeManager` contract to collect all split fees and return any remaining funds to the sender's address (either from the caller or the `Edition` contract) during the minting fee collection process.

However, this recommendation applies only in cases where the Fee asset is the native token.

```diff
    function _collectMintFee(
        IEdition edition_,
        uint256 tokenId_,
        uint256 amount_,
        address payer_,
        address referrer_,
        Fee memory fee_ //@note mintFee information
    ) internal {
        if (fee_.amount == 0) return;

        // For free mints:
        // - Protocol Share = 1/3 of flat fee
        // - Edition Share = 2/3 of flat fee
        //
        // For priced mints:
        // - Protocol Share = 100% of flat fee, shared as follows:
        // - Edition Share = 100% of creator-specified mint cost, 0% of flat fee
        //
        // In both cases, the protocol and edition shares may be split as follows:
        // - Protocol Share
        //   - If a referred mint, mint referrer gets 50% of the protocol share
        //   - If a referred collection, collection referrer gets 25% of the protcol share
        //   - Protocol fee receiver gets the remainder of the protocol share
        // - Edition Share
        //   - Attributions equally split 25% of the edition share, if applicable
        //   - Creator gets the remainder of the edition share

        uint256 protocolFee = protocolFlatFee * amount_;
        uint256 protocolShare;
        if (fee_.amount == protocolFee) {//@note case strategy_.mintFee = 0
            protocolShare = protocolFee * protocolFeeshareBps / MAX_BPS;
        } else {    //@note case strategy_.mintFee > 0
            protocolShare = protocolFee;    //@note = whole flash fee
        }

        _route( //@note transfer fee to fee receiver
            Fee({asset: fee_.asset, amount: fee_.amount - protocolShare}),
            _feeReceivers[getRouteId(edition_, tokenId_)],  //@note to
            payer_  //@note from
        );

        uint256 referrerShare =
            _splitProtocolFee(edition_, fee_.asset, protocolShare, payer_, referrer_);
        
+       uint256 refundExcess = msg.value - fee_.amount;
+        _transfer(fee_.asset, refundExcess, address(this), msg.sender);
        emit FeeCollected(address(edition_), tokenId_, fee_.asset, fee_.amount, referrerShare);
    }
```

Duplicate of #269

**Comment by ZdravkoHr** [comment]
Escalate 

Dup of #269

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> Dup of #269 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ZdravkoHr](https://github.com/sherlock-audit/2024-04-titles-judging/issues/63/#issuecomment-2108123527): accepted
