### ISSUE TITLE
jecikpo - Edition contract not compatible with ERC2981

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#64]
jecikpo

medium

# Edition contract not compatible with ERC2981

## Summary
The `Edition` contract is not compatible with the ERC2981 standard as the implementation of the `supportsInterface()` is done incorrectly.

## Vulnerability Detail
The` Edition` contracts inherits (among others) ERC1155 and ERC2981. Both of those contracts require specific implementation of the `supportsInterface()`. It is overrides methods from both contracts:
```solidity
    function supportsInterface(bytes4 interfaceId)
        public
        view
        override(IEdition, ERC1155, ERC2981)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
```
The `super` solidity keyword here is used to call functions from both of the inherited contracts, however when the return value is considerd only the ERC1155 value is taken into account. 

contract supporting ERC2981 should return `true` when `supportsInterface()` is called with the following values:
- `0x01ffc9a7`
- `0x2a55205a`

In case the latter value is passed to the `supportsInterface()`, the ERC2981 original method gets called, however its return value is overwritted by ERC1155 return value. and `ERC1155.supportsInterface()` does not return `true` for `0x2a55205a`.

## Impact
Protocol not compatible with ERC2981, hence integration with other protocols might fail. As per the FAQ strict implementation of 1271 (Graph), 712 (Graph, Edition), 2981 (Edition), 1155 (Edition) is required.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L471

## Tool used
Manual Review

## Recommendation
The following code change is recommended:
```diff
    {
-        return super.supportsInterface(interfaceId);
+        return ERC1155.supportsInterface(interfaceId) || ERC2981.supportsInterface(interfaceId);
    }
```

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/titlesnyc/wallflower-contract-v2/pull/1
