### ISSUE TITLE
IllIllI - Future integrations requiring `mintBatch()` will be broken

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#67]
IllIllI

medium

# Future integrations requiring `mintBatch()` will be broken

## Summary
Future integrations requiring `mintBatch()` will be broken

## Vulnerability Detail
`mintBatch()` is supposed to pay separate mint fees based on each item in the batch, but it uses `msg.value` for each loop, rather than sending only the portion specific to that batch entry. After the first iteration of the loop, there will be no more funds to transfer, and it will have over-sent for the first entry in the batch.

## Impact
The `mintBatch()` function is effectively broken. The README states:

```markdown
### Q: Should potential issues, like broken assumptions about function behavior, be reported if they could pose risks in future integrations, even if they might not be an issue in the context of the scope? If yes, can you elaborate on properties/invariants that should hold?
Yes.
```
and any future integration that requires this function will be broken.

## Code Snippet

```solidity
File: src/editions/Edition.sol

283          for (uint256 i = 0; i < tokenIds_.length; i++) {
284              Work storage work = works[tokenIds_[i]];
285  
286              // wake-disable-next-line reentrancy
287 @>           FEE_MANAGER.collectMintFee{value: msg.value}(
288                  this, tokenIds_[i], amounts_[i], msg.sender, address(0), work.strategy
289              );
290  
291              _checkTime(work.opensAt, work.closesAt);
292              _updateSupply(work, amounts_[i]);
293:         }
```
https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L283-L293

## Tool used

Manual Review

## Recommendation

Send `amounts_[i]` rather than `msg.value` for each iteration

Duplicate of #280

**Comment by IllIllI000** [comment]
@WangSecurity duplicate of #280

**Comment by midori-fuse** [comment]
@WangSecurity I remember you rejecting to dupe an issue post-esc before. I'm all for resolving things post-esc, but there may be some standards needed after this or a post-esc duping process.

For fair treatment, #48 is a dupe of #280 as well. #121 of #267, and #159 of #269 (there may be more). But these are unresolved ones flagged in the Discord channel and/or commented on the issue itself.

**Comment by WangSecurity** [comment]
Yep, you're correct @midori-fuse, it's just the fact that this contest had a lot of problems with duplicates so I'm more easy with that. In general yes, there is a small chance that unescalated issues will addressed, this contest with lots of incorrect duplicates is exception. Thank you for flagging!
