### ISSUE TITLE
ubl4nk - User can mint all the maxSupply through Edition::mintBatch

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#70]
ubl4nk

high

# User can mint all the maxSupply through Edition::mintBatch

## Summary
Edition::mintBatch is not implemented correctly and due to it, a user pays the mint fee for only 1 token, but mints all the maxSupply of a work.
## Vulnerability Detail
User calls the function `mintBatch`:
```solidity
function mintBatch(
        address[] calldata receivers_,
        uint256 tokenId_,
        uint256 amount_,
        bytes calldata data_
    ) external payable {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, address(0), works[tokenId_].strategy
        );

        for (uint256 i = 0; i < receivers_.length; i++) {
            _issue(receivers_[i], tokenId_, amount_, data_);
        }

        _refundExcess();
    }
```
for the `receivers_` array, the user enters for example 100 different addresses and for `amount_`, he enters value `1`.
when it comes to this line:
```solidity
FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, address(0), works[tokenId_].strategy
        );
```
due to that the `amount_` is `1`, so the user should pay only the mint fee for 1 token and it continues:
```solidity
for (uint256 i = 0; i < receivers_.length; i++) {
            _issue(receivers_[i], tokenId_, amount_, data_);
        }
```
in this loop, due to that the `receivers_` array has 100 items, so 100 tokens will be minted (each receiver will receive 1 token).
## Impact
User will pay the fee for 1 token, but mints all the maxSupply of a work.
## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L304-L320
## Tool used

Manual Review

## Recommendation
Consider calculating the mint fee based on number of items inside the `receivers_` array and `amount_`.

Duplicate of #264

**Comment by Alireza-Razavi** [comment]
escalate
This is duplicate of #264

**Comment by sherlock-admin3** [comment]
> escalate
> This is duplicate of #264
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #264

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #264

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [alireza-razavi](https://github.com/sherlock-audit/2024-04-titles-judging/issues/70/#issuecomment-2107203616): accepted
