### ISSUE TITLE
juan - The excess funds sent to Edition will be lost, since `_refundExcess` has a logical flaw

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#73]
juan

high

# The excess funds sent to Edition will be lost, since `_refundExcess` has a logical flaw

## Summary
The protocol expects that excess eth may be sent when calling `Edition.mint()`, `Edition.mintBatch()`, etc. Because of this, `_refundExcess()` is employed to return any excess ether obtained. However, since `msg.value` is completely sent off to the `FeeManager` contract, the excess funds will be moved to the `FeeManager` and won't be refunded by `_refundExcess()`.

## Vulnerability Detail
```solidity
function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {

        // Here, all the funds are sent to the FeeManager
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy //@audit malicious strategy?
        );

        _issue(to_, tokenId_, amount_, data_);

        // since address(this).balance == 0, this won't do anything
        _refundExcess();
    }
```
Clearly as demonstrated by the above comments, the intended refund feature is non-functional.

## Impact
The intended refund feature will never work, leading to lost funds for users whenever they call `mint()`, `mintBatch()`, `mintWithComment()`

## Code Snippet
**Edition.mint()**
https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L228-L242

**_refundExcess()**
https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L512-L516
## Tool used

Manual Review

## Recommendation
Calculate the required fee before sending it into the FeeManager via `FeeManager.collectMintFee{value: requiredFee}()`

Duplicate of #269

**Comment by 0xjuaan** [comment]
Escalate

Valid dupe of #269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Valid dupe of #269 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-04-titles-judging/issues/73/#issuecomment-2106291272): accepted
