### ISSUE TITLE
Krace - The signature for a proxied acknowledgment could be replayed on a different chain

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#8]
Krace

high

# The signature for a proxied acknowledgment could be replayed on a different chain

## Summary

The creator of the `to` Node can utilize an ECDSA signature to either acknowledge or unacknowledge an Edge. However, since the signature does not specify the target chainId, a malicious user could replay the signature on a different chain. This directly compromises the functionality of the acknowledgment function.

## Vulnerability Detail

The ECDSA signature only contains information about the `edgeId` and `data`, without specifying the traget chainId. A malicious user could replay the signature on a different chain to execute the acknowledge operation, thereby breaking the intended functionality.

```solidity
    /// @notice Modified to check the signature for a proxied acknowledgment.
    modifier checkSignature(bytes32 edgeId, bytes calldata data, bytes calldata signature) {
        bytes32 digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data)));
        if (
            !edges[edgeId].to.creator.target.isValidSignatureNowCalldata(digest, signature)
                || _isUsed[keccak256(signature)]
        ) {
            revert Unauthorized();
        }
        _;
        _isUsed[keccak256(signature)] = true;
    }
```

## Impact

The core functionality of the acknowledgment/unacknowledgment mechanism with ECDSA signatures is compromised.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/graph/TitlesGraph.sol#L40-L50

## Tool used

Manual Review

## Recommendation

Include the chainId in the signature.

**Comment by ccashwell** [comment]
This is not valid. Indeed, the chainId is being validated as part of the EIP712 domain. 

<img width="581" alt="image" src="https://github.com/sherlock-audit/2024-04-titles-judging/assets/184242/b13771ae-8625-4a18-9c09-a52e53c302e1">
