### ISSUE TITLE
cu5t0mPe0 - The _refundExcess function cannot refund

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#80]
cu5t0mPe0

medium

# The _refundExcess function cannot refund

## Summary

The _refundExcess function cannot refund because there is no excess amount in the Edition contract

## Vulnerability Detail

The _refundExcess function cannot perform a normal refund because when calling `collectMintFee`, all the amount sent by the user has been sent to FeeManager for storage, which will cause the user to lose the amount. However, since the administrator can be contacted to call `FeeManager::withdraw `function, so the user's amount can be refunded, so I judge this vulnerability as Medium.

## Impact

The refund function cannot refund

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L228-L242

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L252-L270

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L304-L320

## Tool used

Manual Review

## Recommendation

The excess amount should be sent back to the Edition contract from the FeeManager.

Duplicate of #269

**Comment by cu5t0mPeo** [comment]
Escalated
Same as this report:https://github.com/sherlock-audit/2024-04-titles-judging/issues/269

**Comment by sherlock-admin3** [comment]
> Escalated
> Same as this report:https://github.com/sherlock-audit/2024-04-titles-judging/issues/269

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cu5t0mPeo](https://github.com/sherlock-audit/2024-04-titles-judging/issues/80/#issuecomment-2109775303): accepted
