### ISSUE TITLE
cu5t0mPe0 - MintBatch function not working

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#81]
cu5t0mPe0

medium

# MintBatch function not working

## Summary

MintBatch function not working

## Vulnerability Detail

The MintBatch function cannot be used normally. The reason is that when users use MintBatch for loop casting, they need to send the amount to the FeeManager. However, the problem occurs in that the eth of `msg.value` is sent to the FeeManager in each loop. This occurs in the second loop. , it will cause the amount in the Edition contract to be insufficient, making this function unable to run normally.

The following is the implementation code of mintBatch:

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L277-L297

## Impact

MintBatch function not working

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L277-L297

## Tool used

Manual Review

## Recommendation

should be calculated before looping `msg.value/tokenIds_.length (roundup)` 

Duplicate of #280

**Comment by cu5t0mPeo** [comment]
Escalated
Same as this report:https://github.com/sherlock-audit/2024-04-titles-judging/issues/280

**Comment by sherlock-admin3** [comment]
> Escalated
> Same as this report:https://github.com/sherlock-audit/2024-04-titles-judging/issues/280

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #280

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #280

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cu5t0mPeo](https://github.com/sherlock-audit/2024-04-titles-judging/issues/81/#issuecomment-2109769015): accepted
