### ISSUE TITLE
cu5t0mPe0 - Users only need to pay a small amount to mint many tokens

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#85]
cu5t0mPe0

high

# Users only need to pay a small amount to mint many tokens

## Summary

mintBatch is not fully checked

## Vulnerability Detail

When collectMintFee calculates mint fee, the calculation formula is `amount * (strategy_.mintFee + protocolFlatFee)`.

calculates mint fee：

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/fees/FeeManager.sol#L250-L257

Users can use the mintBatch function to send minted tokens to different recipients, but this aspect has not been considered in the fee calculation.

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L304-L320

The actual amount parameter passed to `collectMintFee` should be `amount_ * receivers_.length`.

Ultimately, attackers can pass an amount parameter of 1, but increase the size of the receivers array, thereby resulting in minting a very large number of tokens.

## Impact

Users only need to pay a small amount to mint many tokens

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/c9d16782a7d3c15c7a759f22c9e0552d5e777ed7/wallflower-contract-v2/src/editions/Edition.sol#L304-L320

## Tool used

Manual Review

## Recommendation

Change `amount_` to `amount_ * receivers_`

Duplicate of #264

**Comment by cu5t0mPeo** [comment]
Escalated
Same as this report:https://github.com/sherlock-audit/2024-04-titles-judging/issues/264

**Comment by sherlock-admin3** [comment]
> Escalated
> Same as this report:https://github.com/sherlock-audit/2024-04-titles-judging/issues/264

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #264

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #264

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cu5t0mPeo](https://github.com/sherlock-audit/2024-04-titles-judging/issues/85/#issuecomment-2109772974): accepted
