### ISSUE TITLE
jecikpo - Possible loss of Ether during minting process

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#86]
jecikpo

medium

# Possible loss of Ether during minting process

## Summary
When a user calls one of the following functions:
- `Edition.mint()`
- `Edition.mintWithComment()`
- `Edition.mintBatch()` (both)
all supplied Ether shall be transferred to the to the `FeeManager` for fees collection. If the Ether amount is greater than the needed fees, the remaining amount will be left on the FeeManager. There is no mechanism for the minting user to retrieve excess amount of Ether due to incorrect implementation.

## Vulnerability Detail
When one of the above minting functions is called, `msg.value` amount of ether is sent to the `FeeManager` as per the following code:
```solidity
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );
```
The `FeeManager` shall then proceed with fee calculation and shall distribute the fees based on many other factors. However the remaining Ether is not returned to the `Edition` contract. That means that the `_refundExcess()` which sits at the end of each of the listed minting functions, shall do nothing.

The excess Ether that is left on the `FeeManager` could either be withdrawn by the protocol team using `withdraw()` or it could be used by the next minter who could just supply the remaining Ether during minting so that his Ether sent + the Ether sitting on `FeeManager` could be just enough to satisfy the necessary fee amount. 

We can see that each minting function calls the `_refundExcess()` at its end. Hence the original design was that the `Edition` supplies the necessary Ether to the `FeeManager` and if there is an excess then it is transferred back to the caller.

## Impact
Loss of excess Ether by the minter.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L236

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L262

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L287

https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/editions/Edition.sol#L311

## Tool used
Manual Review

## Recommendation
It is necessary to change the code so that the amount of Ether fees sent is calculated within the `Edition` contract and the required amount is sent to the `FeeManager` instead of `msg.value`. This way the `_refundExcess()` could work.

Duplicate of #269

**Comment by jecikpo** [comment]
Escalate

This is duplicate of: https://github.com/sherlock-audit/2024-04-titles-judging/issues/269#issue-2266045289

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is duplicate of: https://github.com/sherlock-audit/2024-04-titles-judging/issues/269#issue-2266045289

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [jecikpo](https://github.com/sherlock-audit/2024-04-titles-judging/issues/86/#issuecomment-2107414516): accepted

**Comment by jecikpo** [comment]
@WangSecurity thank you!
