### ISSUE TITLE
1337 - graph in TitlesCore can not be upgraded

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#87]
1337

medium

# graph in TitlesCore can not be upgraded

## Summary
TitlesGraph is UUPSUpgradeable, which means that it is designed to be upgradeable. But the way how TitlesCore new it makes it unupgradeable.

## Vulnerability Detail
In TitlesCore, `graph = new TitlesGraph(address(this), msg.sender);`
```solidity
    function initialize(address feeReceiver_, address splitFactory_) external initializer {
        _initializeOwner(msg.sender);

        feeManager = new FeeManager(msg.sender, feeReceiver_, splitFactory_);
        graph = new TitlesGraph(address(this), msg.sender);
    }
```
Then graph is Instance contract but proxy contract, which means it is unupgradeable.

## Impact
graph in TitlesCore is unupgradeable.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/TitlesCore.sol#L48
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L17

## Tool used
Manual Review

## Recommendation
We should use `LibClone.deployERC1967`.

Duplicate of #445

**Comment by sherlock-admin2** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/titlesnyc/wallflower-contract-v2/pull/1

**Comment by sherlock-admin2** [comment]
The Lead Senior Watson signed off on the fix.
