### ISSUE TITLE
1337 - Signature malleability allows replay attacks in Titlesgraph when acknowledgeEdge and unacknowledgeEdge

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#9]
1337

high

# Signature malleability allows replay attacks in Titlesgraph when acknowledgeEdge and unacknowledgeEdge

## Summary
Signature malleability allows replay attacks in smart contract functions using ECDSA signatures for authorization.

## Vulnerability Detail
The contract relies on ECDSA signatures for the validation of critical operations in functions like `acknowledgeEdge` and `unacknowledgeEdge`. Due to the malleability of ECDSA signatures, it is possible to alter a valid signature in such a way that it remains valid but results in a different hash when checked using _isUsed[keccak256(signature)]. This makes it possible to replay the signature for unauthorized operations by https://medium.com/draftkings-engineering/signature-malleability-7a804429b14a . 

## Impact
Attackers can repeatedly use manipulated signatures to authorize transactions that should only be possible once, potentially leading to unauthorized state changes or other malicious activities within the contract. For example, attackers can call `acknowledgeEdge` after    
`unacknowledgeEdge` if he had a valid signature before (if he call `acknowledgeEdge` before, he had a valid signature).

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L40
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L118
https://github.com/sherlock-audit/2024-04-titles/blob/main/wallflower-contract-v2/src/graph/TitlesGraph.sol#L146
## Tool used

Manual Review

## Recommendation
Add `nonce` field when calc `bytes32 digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data)));` i.e. we may calc `bytes32 digest = _hashTypedData(keccak256(abi.encode(ACK_TYPEHASH, edgeId, data, nonce)));` If success, `nonce++`;

Duplicate of #279

**Comment by MageIntern** [comment]
Escalate 

it is dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/279, not 284. and 279 is not dup as 273

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> it is dup of https://github.com/sherlock-audit/2024-04-titles-judging/issues/279, not 284. and 279 is not dup as 273

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #279

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #279

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [MageIntern](https://github.com/sherlock-audit/2024-04-titles-judging/issues/9/#issuecomment-2106709620): accepted
