### ISSUE TITLE
cu5t0mPe0 - The creator may not receive the deserved fee.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-04-titles-judging#92]
cu5t0mPe0

high

# The creator may not receive the deserved fee.

## Summary

When the creator transfers, the change in fee receiver is not considered.

## Vulnerability Detail

When users call the `transferWork` function to transfer the Edition's creator to someone else, the fee receiver does not change accordingly, and there is no related set function in the feeManager. As a result, the new creator may lose the deserved amount.

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L412-L420

## Impact

the new creator may lose the deserved amount.

## Code Snippet

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L412-L420

## Tool used

Manual Review

## Recommendation

When setting a new creator, the fee receiver should also be changed.

Duplicate of #283

**Comment by ccashwell** [comment]
Won't fix, this is expected behavior

**Comment by cu5t0mPeo** [comment]
Escalated
Same as this report:https://github.com/sherlock-audit/2024-04-titles-judging/issues/283
but my report refused

**Comment by sherlock-admin3** [comment]
> Escalated
> Same as this report:https://github.com/sherlock-audit/2024-04-titles-judging/issues/283
> but my report refused

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #283

**Comment by Evert0x** [comment]
Result:
Medium
Duplicate of #283

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [cu5t0mPeo](https://github.com/sherlock-audit/2024-04-titles-judging/issues/92/#issuecomment-2109893857): accepted
