### ISSUE TITLE
mt030d - Excess funds are not refunded during the minting

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-04-titles-judging#99]
mt030d

medium

# Excess funds are not refunded during the minting

## Summary
Excess funds are not refunded during the minting.

## Vulnerability Detail
```solidity
    function mint(
        address to_,
        uint256 tokenId_,
        uint256 amount_,
        address referrer_,
        bytes calldata data_
    ) external payable override {
        // wake-disable-next-line reentrancy
        FEE_MANAGER.collectMintFee{value: msg.value}(
            this, tokenId_, amount_, msg.sender, referrer_, works[tokenId_].strategy
        );

        _issue(to_, tokenId_, amount_, data_);
        _refundExcess();
    }
```
```solidity
    /// @notice Refund any excess ETH sent to the contract.
    /// @dev This function is called after minting tokens to refund any ETH left in the contract after all fees have been collected.
    function _refundExcess() internal {
        if (msg.value > 0 && address(this).balance > 0) {
            msg.sender.safeTransferETH(address(this).balance);
        }
    }
```
To refund excess ETH to the sender during the minting, the ﻿`mint()` function in the `Edition` contract calls ﻿`_refundExcess()` at the end. However, before ﻿`_refundExcess()` is called, all ﻿`msg.value` are transferred to the ﻿`FEE_MANAGER` in the ﻿`collectMintFee()` call, leaving no ETH for refunding.
If a user inputs more ETH than necessary as ﻿`msg.value` during the ﻿`mint()` call, the excess ETH goes to the ﻿`FEE_MANAGER` contract. This excess ETH can only be withdrawn by the owner or admin of ﻿FEE_MANAGER using its ﻿withdraw() function. In other words, if a user accidentally inputs more ETH than needed, the excess ETH is not refunded to them.
This issue also applies to the `mintWithComment()` and `mintBatch()` functions in the `Edition` contract.

## Impact

If a user accidentally inputs more ETH than needed, the excess ETH is not refunded to them.

## Code Snippet
https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L510-L516

https://github.com/sherlock-audit/2024-04-titles/blob/d7f60952df22da00b772db5d3a8272a988546089/wallflower-contract-v2/src/editions/Edition.sol#L228-L242

## Tool used

Manual Review

## Recommendation
In the family of mint functions, only forward the necessary fee to the ﻿FEE_MANAGER in the ﻿collectMintFee() call, and refund any excess ETH to the sender.

Duplicate of #269

**Comment by TradMod** [comment]
Escalate

This finding is a valid dup of #269

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This finding is a valid dup of #269

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by WangSecurity** [comment]
Agree with the escalation, planning to accept and duplicate with #269

**Comment by Evert0x** [comment]
Result:
High
Duplicate of #269

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ShaheenRehman](https://github.com/sherlock-audit/2024-04-titles-judging/issues/99/#issuecomment-2106797305): accepted
